import {NextRequest,NextResponse} from "next/server";
import {getCurrentUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {assertSameOrigin,jsonError} from "@/lib/http";
import {getCurrentStorefront} from "@/lib/storefront";
import {parseAccountConfig} from "@/lib/account-config";
import {restoreAccountCartLine} from "@/lib/account-cart-pricing";
import {savedCartSchema,mergeSavedCart,savedCartRevision} from "@/lib/account-cart";
import {z} from "zod";
const schema=z.object({lines:savedCartSchema,revision:z.string().optional()});
async function save(request:NextRequest,merge:boolean){if(!assertSameOrigin(request))return jsonError("Invalid origin",403);const [user,store]=await Promise.all([getCurrentUser(),getCurrentStorefront()]);if(!user)return jsonError("Unauthorised",401);if(!parseAccountConfig(store.accountConfig).savedCartEnabled)return jsonError("Saved carts disabled",404);const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return jsonError("Invalid cart");const data=await db.$transaction(async tx=>{await tx.user.update({where:{id:user.id},data:{updatedAt:new Date()}});const existing=await tx.customerAccountData.findUnique({where:{storeId_userId:{storeId:store.id,userId:user.id}}});if(!merge && existing && parsed.data.revision!==savedCartRevision(existing.cart))return null;const remote=savedCartSchema.safeParse(existing?.cart);const lines=merge?mergeSavedCart(remote.success?remote.data:[],parsed.data.lines):parsed.data.lines;const variants=await tx.productVariant.findMany({where:{id:{in:lines.map(l=>l.variantId)},active:true,product:{storeId:store.id,status:"ACTIVE",shopVisible:true,category:{storeId:store.id,status:"PUBLISHED"}}},include:{product:{include:{options:{where:{active:true},include:{values:true}}}}}});const restored=lines.flatMap(line=>{const variant=variants.find(v=>v.id===line.variantId);if(!variant)return [];try{return [restoreAccountCartLine(line,variant)];}catch{return [];}});const valid=restored.map(({variantId,quantity,personalisationChoice,personalisation})=>({variantId,quantity,personalisationChoice,personalisation}));const saved=await tx.customerAccountData.upsert({where:{storeId_userId:{storeId:store.id,userId:user.id}},create:{storeId:store.id,userId:user.id,cart:valid},update:{cart:valid}});return {revision:savedCartRevision(saved.cart),lines:restored,removedCount:lines.length-restored.length};});return data?NextResponse.json(data,{headers:{"cache-control":"no-store"}}):jsonError("Cart changed on another device. Reload to merge your carts.",409);}
export function POST(request:NextRequest){return save(request,true);}
export function PUT(request:NextRequest){return save(request,false);}
