import {NextRequest,NextResponse} from "next/server";
import {getCurrentUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {assertSameOrigin,jsonError} from "@/lib/http";
import {getCurrentStorefront} from "@/lib/storefront";
import {parseAccountConfig} from "@/lib/account-config";
import {savedCartSchema,savedLineKey,mergeSavedCart} from "@/lib/account-cart";
import {z} from "zod";
const schema=z.object({lines:savedCartSchema,revision:z.string().optional()});
async function save(request:NextRequest,merge:boolean){if(!assertSameOrigin(request))return jsonError("Invalid origin",403);const [user,store]=await Promise.all([getCurrentUser(),getCurrentStorefront()]);if(!user)return jsonError("Unauthorised",401);if(!parseAccountConfig(store.accountConfig).savedCartEnabled)return jsonError("Saved carts disabled",404);const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return jsonError("Invalid cart");const data=await db.$transaction(async tx=>{await tx.user.update({where:{id:user.id},data:{updatedAt:new Date()}});const existing=await tx.customerAccountData.findUnique({where:{storeId_userId:{storeId:store.id,userId:user.id}}});if(!merge && existing && parsed.data.revision!==existing.updatedAt.toISOString())return null;const remote=savedCartSchema.safeParse(existing?.cart);const lines=merge?mergeSavedCart(remote.success?remote.data:[],parsed.data.lines):parsed.data.lines;const variants=await tx.productVariant.findMany({where:{id:{in:lines.map(l=>l.variantId)},active:true,product:{storeId:store.id,status:"ACTIVE"}},select:{id:true,name:true,priceCents:true,product:{select:{name:true}}}});const valid=lines.filter(l=>variants.some(v=>v.id===l.variantId));const saved=await tx.customerAccountData.upsert({where:{storeId_userId:{storeId:store.id,userId:user.id}},create:{storeId:store.id,userId:user.id,cart:valid},update:{cart:valid}});return {revision:saved.updatedAt.toISOString(),lines:valid.map(line=>{const variant=variants.find(v=>v.id===line.variantId)!;return {...line,key:savedLineKey(line),productName:variant.product.name,variantName:variant.name,unitPriceCents:variant.priceCents};})};});return data?NextResponse.json(data,{headers:{"cache-control":"no-store"}}):jsonError("Cart changed on another device. Reload to merge your carts.",409);}
export function POST(request:NextRequest){return save(request,true);}
export function PUT(request:NextRequest){return save(request,false);}
