import { NextRequest,NextResponse } from "next/server";
import { getAdminApiContext } from "@/lib/admin";
import { db } from "@/lib/db";
import { assertSameOrigin,jsonError } from "@/lib/http";
import { teamAccessSchema } from "@/lib/team-access";
import { z } from "zod";
import { createOpaqueToken,sha256 } from "@/lib/crypto";
import { sendTransactionalEmail } from "@/lib/email";
const schema=teamAccessSchema.extend({email:z.string().trim().toLowerCase().email()});
export async function POST(request:NextRequest){if(!assertSameOrigin(request))return jsonError("Invalid origin",403);const context=await getAdminApiContext();if(!context?.isPlatformAdmin)return jsonError("Principal administrator required",403);const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success||(!parsed.data.roles.length&&!parsed.data.permissions.length))return jsonError("Enter an email and select access");const token=createOpaqueToken();const invitation=await db.$transaction(async tx=>{await tx.store.update({where:{id:context.store.id},data:{updatedAt:new Date()}});await tx.teamInvitation.updateMany({where:{storeId:context.store.id,email:parsed.data.email,acceptedAt:null,revokedAt:null},data:{revokedAt:new Date()}});return tx.teamInvitation.create({data:{storeId:context.store.id,email:parsed.data.email,roles:parsed.data.roles,permissions:parsed.data.permissions,invitedBy:context.user.id,tokenHash:sha256(token),expiresAt:new Date(Date.now()+7*86400000)}});});await db.auditLog.create({data:{actorId:context.user.id,storeId:context.store.id,action:"TEAM_INVITATION_CREATED",entityType:"TeamInvitation",entityId:invitation.id}});let sent=false;try{sent=await sendTransactionalEmail({to:invitation.email,subject:`Invitation to manage ${context.store.displayName}`,text:`You have been invited to the ${context.store.displayName} operations team. Sign in or create and verify an account using this email, then accept your invitation: ${context.store.origin}/dashboard/team-invitation?token=${encodeURIComponent(token)}\nThis invitation expires in 7 days.`,storeSlug:context.store.slug,category:"account"});}catch{}return NextResponse.json({ok:true,sent},{status:201});}
