import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { cache } from "react";
import { ArrowRight, Check, Radio } from "lucide-react";
import { categoryBenefits, categoryFaq, categorySections, categorySteps } from "@/lib/category-content";
import { db } from "@/lib/db";

const getCategory = cache((slug: string) => db.productCategory.findFirst({ where: { slug, status: "PUBLISHED", showLanding: true }, include: { products: { where: { status: "ACTIVE", shopVisible: true }, include: { images: { where: { isPrimary: true }, take: 1 }, variants: { where: { active: true }, orderBy: { priceCents: "asc" } } }, orderBy: [{ featured: "desc" }, { name: "asc" }] } } }));
const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" });

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const category = await getCategory((await params).slug); if (!category) return { robots: { index: false, follow: false } };
  const title = category.seoTitle ?? category.heroHeadline ?? category.name; const description = category.seoDescription ?? category.shortDescription ?? category.description;
  return { title, description, alternates: { canonical: category.canonicalUrl ?? `/categories/${category.slug}` }, robots: category.indexable ? { index: true, follow: true } : { index: false, follow: false }, openGraph: { title, description: description ?? undefined, type: "website", images: category.ogImageUrl ? [category.ogImageUrl] : category.heroImageUrl ? [category.heroImageUrl] : undefined } };
}

export default async function CategoryPage({ params }: { params: Promise<{ slug: string }> }) {
  const category = await getCategory((await params).slug); if (!category) notFound();
  const origin = process.env.APP_URL ?? "http://localhost:3000"; const benefits = categoryBenefits(category.benefits); const steps = categorySteps(category.howItWorks); const sections = categorySections(category.contentSections); const faq = categoryFaq(category.faq); const products = category.showInShop ? category.products : [];
  const shopHref = `/shop?category=${category.slug}`; const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: origin }, { "@type": "ListItem", position: 2, name: "Shop", item: `${origin}/shop` }, { "@type": "ListItem", position: 3, name: category.name, item: `${origin}/categories/${category.slug}` }] }, { "@type": "ItemList", name: category.name, itemListElement: products.map((product, index) => ({ "@type": "ListItem", position: index + 1, url: `${origin}/products/${product.slug}`, name: product.name })) }, ...(faq.length ? [{ "@type": "FAQPage", mainEntity: faq.map(item => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }] : [])] };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replaceAll("<", "\\u003c") }} /><section className="category-landing"><nav className="breadcrumbs category-breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/shop">Shop</Link><span>/</span><span>{category.name}</span></nav><div className="category-landing-hero"><div><span className="eyebrow">{category.heroEyebrow ?? "Tapkin smart collection"}</span><h1>{category.heroHeadline ?? category.name}</h1><p className="lead">{category.heroDescription ?? category.shortDescription ?? category.description}</p><div className="actions"><Link className="button" href={category.ctaHref || shopHref}>{category.ctaLabel ?? `Shop ${category.name}`} <ArrowRight size={17} /></Link>{category.secondaryCtaLabel && category.secondaryCtaHref && <Link className="button secondary" href={category.secondaryCtaHref}>{category.secondaryCtaLabel}</Link>}</div></div>{category.heroImageUrl ? <Image src={category.heroImageUrl} alt={`${category.name} smart products`} width={900} height={720} priority unoptimized /> : <div className="category-hero-placeholder"><Radio size={58} /><strong>{category.name}</strong><span>NFC + QR + 3D printing</span></div>}</div>
    {benefits.length > 0 && <section className="category-benefits"><div className="section-head"><span className="eyebrow">Why it matters</span><h2>Designed around {category.name.toLowerCase()}.</h2></div><div className="benefit-grid">{benefits.map(item => <article key={`${item.order}-${item.title}`}><span className="icon"><Check /></span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>}
    {steps.length > 0 && <section className="category-steps"><div className="section-head"><span className="eyebrow">Simple. Fast. Useful.</span><h2>How it works</h2></div><div className="step-grid">{steps.map((step, index) => <article key={`${step.order}-${step.title}`}><span className="step-number">{index + 1}</span>{step.imageUrl && <Image src={step.imageUrl} alt="" width={560} height={380} unoptimized />}<h3>{step.title}</h3><p>{step.description}</p>{step.ctaLabel && step.ctaHref && <Link href={step.ctaHref}>{step.ctaLabel} <ArrowRight size={15} /></Link>}</article>)}</div></section>}
    {sections.map(section => <section className={`category-story ${section.layout.toLowerCase().replaceAll("_", "-")}`} key={`${section.order}-${section.heading}`}><div>{section.eyebrow && <span className="eyebrow">{section.eyebrow}</span>}<h2>{section.heading}</h2><p>{section.copy}</p>{section.bulletPoints.length > 0 && <ul>{section.bulletPoints.map(item => <li key={item}><Check size={18} />{item}</li>)}</ul>}{section.ctaLabel && section.ctaHref && <Link className="button secondary" href={section.ctaHref}>{section.ctaLabel}</Link>}</div>{section.imageUrl && section.layout !== "TEXT_ONLY" && <Image src={section.imageUrl} alt="" width={760} height={600} unoptimized />}</section>)}
    <section className="category-products"><div className="section-head"><span className="eyebrow">Made to be yours</span><h2>Explore the {category.name} collection.</h2></div><div className="shop-grid">{products.map(product => <article className="card product-card" key={product.id}>{product.images[0] && <Image className="category-product-image" src={product.images[0].url} alt={product.images[0].altText} width={500} height={500} unoptimized />}<h3>{product.name}</h3><p>{product.shortDescription ?? product.description}</p>{product.variants[0] && <strong className="price">From {money.format(product.variants[0].priceCents / 100)}</strong>}<Link className="button" href={`/products/${product.slug}`}>View product</Link></article>)}</div>{!products.length && <div className="admin-empty">This collection is not accepting new orders right now.</div>}</section>
    {faq.length > 0 && <section className="faq-section category-faq"><div className="section-head"><span className="eyebrow">Helpful answers</span><h2>Frequently asked questions</h2></div>{faq.map(item => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>}
  </section></>;
}
