import { PrintAgentRegistration } from "@/components/print-agent-registration";
import { requireAdminPageContext } from "@/lib/admin";
import { db } from "@/lib/db";

export default async function AdminShippingPage() {
  const { store, storeRole, isPlatformAdmin } = await requireAdminPageContext();
  const [origins, packaging, zones, providers, agents, jobs] = await Promise.all([
    db.shippingOrigin.findMany({ where: { storeId: store.id }, orderBy: [{ isDefault: "desc" }, { name: "asc" }] }),
    db.packaging.findMany({ where: { storeId: store.id }, orderBy: { name: "asc" } }),
    db.shippingZone.findMany({ where: { storeId: store.id }, include: { rates: { where: { active: true }, orderBy: { amountCents: "asc" } } }, orderBy: { priority: "desc" } }),
    db.shippingProvider.findMany({ where: { storeId: store.id }, orderBy: { name: "asc" } }),
    db.printAgent.findMany({ where: { storeId: store.id }, orderBy: { createdAt: "desc" } }),
    db.printJob.findMany({ where: { storeId: store.id }, include: { shipment: { select: { trackingNumber: true, order: { select: { orderNumber: true } } } }, printAgent: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 30 }),
  ]);
  const canRegister = isPlatformAdmin || storeRole === "ADMIN";
  return <div><div className="admin-heading"><div><p className="admin-kicker">Sales & fulfilment</p><h1>Shipping</h1><p>Store-scoped origins, packaging, services, labels and local print automation.</p></div></div><div className="admin-grid two"><section className="admin-panel"><h2>Origin</h2>{origins.map(origin => <p key={origin.id}><strong>{origin.name}{origin.isDefault ? " · Default" : ""}</strong><br /><span className="muted">{origin.line1}, {origin.suburb} {origin.state} {origin.postcode}</span></p>)}{!origins.length && <p className="admin-empty">Configure a dispatch origin before quoting.</p>}</section><section className="admin-panel"><h2>Packaging</h2>{packaging.map(item => <p key={item.id}><strong>{item.name}</strong><br /><span className="muted">{item.lengthMm} × {item.widthMm} × {item.heightMm} mm · {item.emptyWeightGrams} g empty</span></p>)}{!packaging.length && <p className="admin-empty">No active packaging.</p>}</section></div><section className="admin-panel"><div className="panel-heading"><div><h2>Zones and rates</h2><p>Manual rates remain the explicit fallback when a carrier adapter is unavailable.</p></div></div>{zones.map(zone => <div className="order-lines" key={zone.id}><article><div><strong>{zone.name}</strong><span>{zone.countries.join(", ")} · {zone.states.length ? zone.states.join(", ") : "All states"}</span></div><div>{zone.rates.map(rate => <span key={rate.id}>{rate.serviceName} · {(rate.amountCents / 100).toLocaleString("en-AU", { style: "currency", currency: store.currency })}</span>)}</div></article></div>)}</section><div className="admin-grid two"><section className="admin-panel"><h2>Providers</h2>{providers.map(provider => <p key={provider.id}><strong>{provider.name}</strong><br /><span className="muted">{provider.kind} · Rates {provider.supportsRates ? "on" : "off"} · Labels {provider.supportsLabels ? "on" : "off"}</span></p>)}</section><section className="admin-panel"><h2>Print agents</h2>{agents.map(agent => <p key={agent.id}><strong>{agent.name}</strong><br /><span className="muted">{agent.printerName || "Default printer"} · {agent.lastSeenAt ? `Last seen ${agent.lastSeenAt.toLocaleString("en-AU")}` : "Never connected"}</span></p>)}{canRegister && <PrintAgentRegistration />}</section></div><section className="admin-panel"><h2>Print queue</h2><div className="table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Tracking</th><th>Status</th><th>Agent</th><th>Attempts</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td>{job.shipment.order.orderNumber}</td><td>{job.shipment.trackingNumber}</td><td><span className={`admin-status ${job.status}`}>{job.status}</span></td><td>{job.printAgent?.name ?? "Unclaimed"}</td><td>{job.attempts}</td></tr>)}</tbody></table></div>{!jobs.length && <p className="admin-empty">No labels queued.</p>}</section></div>;
}
