"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { AccountConfig } from "@/lib/account-config";
export function AccountSettingsForm({config}:{config:AccountConfig}) {
 const router=useRouter();const [message,setMessage]=useState("");const [pending,setPending]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);const data=new FormData(event.currentTarget);const payload={...Object.fromEntries(["googleEnabled","appleEnabled","favouritesEnabled","savedCartEnabled","notificationsEnabled","helpEnabled"].map(key=>[key,data.get(key)==="on"])),helpText:data.get("helpText"),requestTopics:data.getAll("requestTopics")};try{const response=await fetch("/api/admin/account-settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();setMessage(response.ok?"Account settings saved":result.error);if(response.ok)router.refresh();}catch{setMessage("Settings could not be saved. Please try again.");}finally{setPending(false);}}
 return <form className="admin-panel form" onSubmit={submit}><h2>Customer accounts</h2><p>Email sign-in remains available. Provider credentials are configured securely in the server environment.</p>{([ ["googleEnabled","Continue with Google"],["appleEnabled","Continue with Apple"],["favouritesEnabled","Favourites"],["savedCartEnabled","Saved carts"],["notificationsEnabled","Account notifications"],["helpEnabled","Order help menu"] ] as const).map(([key,label])=><label className="check-field" key={key}><input type="checkbox" name={key} defaultChecked={config[key]}/>{label}</label>)}<label className="field">Help text<textarea name="helpText" maxLength={300} defaultValue={config.helpText}/></label><fieldset><legend>Available request topics</legend>{configTopics.map(topic=><label className="check-field" key={topic}><input type="checkbox" name="requestTopics" value={topic} defaultChecked={config.requestTopics.includes(topic)}/>{topic.replaceAll("_"," ")}</label>)}</fieldset><button className="button secondary" disabled={pending}>{pending?"Saving…":"Save account settings"}</button>{message&&<p role="status">{message}</p>}</form>;
}
const configTopics=["ORDER_CHANGE","ADDRESS_CHANGE","CANCELLATION_REQUEST","DELIVERY","QUALITY","OTHER"] as const;
