"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
export function AccountSecurityForm({hasPassword}:{hasPassword:boolean}){
 const [message,setMessage]=useState("");const [pending,setPending]=useState(false);
 async function send(body:Record<string,unknown>){setPending(true);try{const response=await fetch("/api/account/security",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(response.ok?"Security settings updated. Other sessions have been signed out.":result.error);if(response.ok&&body.action==="logout_all")window.location.assign("/login");}catch{setMessage("Please try again.");}finally{setPending(false);}}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);if(data.get("password")!==data.get("confirmPassword"))return setMessage("The new passwords do not match.");void send({action:"password",currentPassword:data.get("currentPassword"),newPassword:data.get("password")});}
 return <div className="account-grid"><section className="card"><h2>Password</h2>{hasPassword?<form className="form" onSubmit={submit}><label className="field">Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label className="field">New password<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><label className="field">Confirm new password<input name="confirmPassword" type="password" minLength={12} autoComplete="new-password" required/></label><p className="fine-print">At least 12 characters, with uppercase, lowercase and a number.</p><button className="button" disabled={pending}>Update password</button></form>:<p>You use a social sign-in. <Link href="/forgot-password"><u>Set a password by verifying your email</u></Link>.</p>}<Link href="/forgot-password">Reset a forgotten password</Link></section><section className="card"><h2>Sessions</h2><p>Sign out on every device, including this one.</p><button className="button secondary" disabled={pending} onClick={()=>{if(window.confirm("Sign out on all devices?"))void send({action:"logout_all"});}}>Sign out everywhere</button>{message&&<p role="status">{message}</p>}</section></div>;
}
