"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, Plus, Trash2 } from "lucide-react";

type VariantForm = { id?: string; sku: string; name: string; colour: string; size: string; material: string; price: string; compareAtPrice: string; cost: string; inventory: number; trackInventory: boolean; lowStockThreshold: number; backorderPolicy: "DENY" | "ALLOW"; active: boolean };
type OptionForm = { id?: string; name: string; code: string; type: "SHORT_TEXT" | "LONG_TEXT" | "SELECT" | "RADIO" | "CHECKBOX" | "COLOUR" | "IMAGE"; required: boolean; maxLength: number | null; price: string; helpText: string; values: string };
export type AdminProductInitial = { id?: string; name: string; slug: string; description: string; fullDescription: string; categoryId: string; type: string; status: string; featured: boolean; brand: string; gstInclusive: boolean; seoTitle: string; seoDescription: string; ogImageUrl: string; canonicalUrl: string; indexable: boolean; variants: VariantForm[]; options: OptionForm[] };

const blankVariant = (): VariantForm => ({ sku: "", name: "Standard", colour: "", size: "", material: "PETG", price: "24.95", compareAtPrice: "", cost: "", inventory: 0, trackInventory: true, lowStockThreshold: 5, backorderPolicy: "DENY", active: true });
const blankOption = (): OptionForm => ({ name: "", code: "", type: "SHORT_TEXT", required: false, maxLength: 40, price: "0", helpText: "", values: "" });
const cents = (value: string) => Math.round(Number(value || 0) * 100);

export function AdminProductForm({ initial, categories }: { initial: AdminProductInitial; categories: Array<{ id: string; name: string }> }) {
  const router = useRouter();
  const [variants, setVariants] = useState<VariantForm[]>(initial.variants.length ? initial.variants : [blankVariant()]);
  const [options, setOptions] = useState<OptionForm[]>(initial.options);
  const [message, setMessage] = useState("");
  const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setMessage("");
    const form = new FormData(event.currentTarget);
    const payload = {
      name: form.get("name"), slug: form.get("slug"), description: form.get("description"), fullDescription: form.get("fullDescription") || null,
      categoryId: form.get("categoryId") || null, type: form.get("type"), status: form.get("status"), featured: form.get("featured") === "on", brand: form.get("brand"), gstInclusive: form.get("gstInclusive") === "on",
      seoTitle: form.get("seoTitle") || null, seoDescription: form.get("seoDescription") || null, ogImageUrl: form.get("ogImageUrl") || "", canonicalUrl: form.get("canonicalUrl") || "", indexable: form.get("indexable") === "on",
      variants: variants.map(variant => ({ ...variant, priceCents: cents(variant.price), compareAtPriceCents: variant.compareAtPrice ? cents(variant.compareAtPrice) : null, costCents: variant.cost ? cents(variant.cost) : null })),
      options: options.map(option => ({ ...option, priceDeltaCents: cents(option.price), values: option.values.split(",").map(value => value.trim()).filter(Boolean).map(value => ({ label: value, value: value.toLowerCase().replace(/\s+/g, "-"), priceDeltaCents: 0, active: true })), active: true })),
    };
    const response = await fetch(initial.id ? `/api/admin/products/${initial.id}` : "/api/admin/products", { method: initial.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json().catch(() => ({})); setPending(false);
    if (!response.ok) return setMessage(result.error ?? "Product could not be saved");
    setMessage("Product saved");
    if (!initial.id) router.replace(`/admin/products/${result.product.id}`); else router.refresh();
  }
  async function archive() {
    if (!initial.id || !window.confirm("Archive this product? It will disappear from the storefront.")) return;
    const response = await fetch(`/api/admin/products/${initial.id}`, { method: "DELETE" });
    if (response.ok) router.push("/admin/products"); else setMessage("Product could not be archived");
  }
  return <form onSubmit={submit} className="admin-form">
    <section className="admin-panel"><div className="panel-heading"><div><h2>Product details</h2><p>Customer-facing information and publication state.</p></div></div><div className="field-grid"><label className="field">Name<input name="name" defaultValue={initial.name} required /></label><label className="field">Slug<input name="slug" defaultValue={initial.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label className="field">Category<select name="categoryId" defaultValue={initial.categoryId}><option value="">Uncategorised</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label className="field">NFC profile type<select name="type" defaultValue={initial.type}>{["PET","CHILD","EMERGENCY","SOCIAL","BUSINESS","LUGGAGE","REVIEW","CUSTOM","ACCESSORY"].map(type => <option key={type}>{type}</option>)}</select></label><label className="field">Status<select name="status" defaultValue={initial.status}>{["DRAFT","ACTIVE","OUT_OF_STOCK","ARCHIVED"].map(status => <option key={status}>{status}</option>)}</select></label><label className="field">Brand<input name="brand" defaultValue={initial.brand} required /></label></div><label className="field">Short description<textarea name="description" defaultValue={initial.description} maxLength={500} required /></label><label className="field">Full description<textarea name="fullDescription" defaultValue={initial.fullDescription} className="large-textarea" /></label><div className="check-row"><label className="check-field"><input type="checkbox" name="featured" defaultChecked={initial.featured} /><span>Featured product</span></label><label className="check-field"><input type="checkbox" name="gstInclusive" defaultChecked={initial.gstInclusive} /><span>Prices include GST</span></label></div></section>
    <section className="admin-panel"><div className="panel-heading"><div><h2>Variants and inventory</h2><p>Each style can have its own SKU, price and stock.</p></div><button className="button secondary" type="button" onClick={() => setVariants(current => [...current, blankVariant()])}><Plus size={16} /> Add variant</button></div><div className="admin-stack">{variants.map((variant, index) => <div className="variant-editor" key={variant.id ?? index}><div className="variant-title"><strong>Variant {index + 1}</strong>{variants.length > 1 && <button type="button" className="icon-button" onClick={() => setVariants(current => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={17} /></button>}</div><div className="field-grid three"><label className="field">SKU<input value={variant.sku} onChange={event => updateVariant(setVariants, index, "sku", event.target.value.toUpperCase())} required /></label><label className="field">Name<input value={variant.name} onChange={event => updateVariant(setVariants, index, "name", event.target.value)} required /></label><label className="field">Material<input value={variant.material} onChange={event => updateVariant(setVariants, index, "material", event.target.value)} /></label><label className="field">Price AUD<input inputMode="decimal" value={variant.price} onChange={event => updateVariant(setVariants, index, "price", event.target.value)} required /></label><label className="field">Compare-at AUD<input inputMode="decimal" value={variant.compareAtPrice} onChange={event => updateVariant(setVariants, index, "compareAtPrice", event.target.value)} /></label><label className="field">Internal cost AUD<input inputMode="decimal" value={variant.cost} onChange={event => updateVariant(setVariants, index, "cost", event.target.value)} /></label><label className="field">Stock<input type="number" min="0" value={variant.inventory} onChange={event => updateVariant(setVariants, index, "inventory", Number(event.target.value))} /></label><label className="field">Low-stock alert<input type="number" min="0" value={variant.lowStockThreshold} onChange={event => updateVariant(setVariants, index, "lowStockThreshold", Number(event.target.value))} /></label><label className="field">Backorders<select value={variant.backorderPolicy} onChange={event => updateVariant(setVariants, index, "backorderPolicy", event.target.value as "DENY" | "ALLOW")}><option value="DENY">Do not allow</option><option value="ALLOW">Allow</option></select></label></div><div className="check-row"><label className="check-field"><input type="checkbox" checked={variant.trackInventory} onChange={event => updateVariant(setVariants, index, "trackInventory", event.target.checked)} /><span>Track inventory</span></label><label className="check-field"><input type="checkbox" checked={variant.active} onChange={event => updateVariant(setVariants, index, "active", event.target.checked)} /><span>Enabled</span></label></div></div>)}</div></section>
    <section className="admin-panel"><div className="panel-heading"><div><h2>Personalisation</h2><p>Define exactly what customers can customise. Selections are frozen on each order.</p></div><button className="button secondary" type="button" onClick={() => setOptions(current => [...current, blankOption()])}><Plus size={16} /> Add field</button></div>{options.length ? <div className="admin-stack">{options.map((option, index) => <div className="variant-editor" key={option.id ?? index}><div className="variant-title"><strong>Field {index + 1}</strong><button type="button" className="icon-button" onClick={() => setOptions(current => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={17} /></button></div><div className="field-grid three"><label className="field">Label<input value={option.name} onChange={event => updateOption(setOptions, index, "name", event.target.value)} required /></label><label className="field">Code<input value={option.code} onChange={event => updateOption(setOptions, index, "code", event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""))} required /></label><label className="field">Input type<select value={option.type} onChange={event => updateOption(setOptions, index, "type", event.target.value as OptionForm["type"])}>{["SHORT_TEXT","LONG_TEXT","SELECT","RADIO","CHECKBOX","COLOUR","IMAGE"].map(type => <option key={type}>{type}</option>)}</select></label><label className="field">Max length<input type="number" min="1" value={option.maxLength ?? ""} onChange={event => updateOption(setOptions, index, "maxLength", event.target.value ? Number(event.target.value) : null)} /></label><label className="field">Additional price AUD<input value={option.price} onChange={event => updateOption(setOptions, index, "price", event.target.value)} /></label><label className="field">Choices, comma separated<input value={option.values} onChange={event => updateOption(setOptions, index, "values", event.target.value)} placeholder="Black, White, Ocean" /></label></div><label className="check-field"><input type="checkbox" checked={option.required} onChange={event => updateOption(setOptions, index, "required", event.target.checked)} /><span>Required</span></label></div>)}</div> : <div className="admin-empty">No personalisation fields. Add one for names, colours, shapes or other made-to-order choices.</div>}</section>
    <section className="admin-panel"><div className="panel-heading"><div><h2>Search and social</h2><p>Optional overrides; strong defaults are generated automatically.</p></div></div><div className="field-grid"><label className="field">SEO title<input name="seoTitle" defaultValue={initial.seoTitle} maxLength={70} /></label><label className="field">Meta description<input name="seoDescription" defaultValue={initial.seoDescription} maxLength={170} /></label><label className="field">Canonical URL<input name="canonicalUrl" type="url" defaultValue={initial.canonicalUrl} /></label><label className="field">Social image URL<input name="ogImageUrl" type="url" defaultValue={initial.ogImageUrl} /></label></div><label className="check-field"><input type="checkbox" name="indexable" defaultChecked={initial.indexable} /><span>Allow search engines to index this product</span></label></section>
    {message && <div className={message === "Product saved" ? "notice" : "form-error"} role="status">{message}</div>}<div className="admin-form-actions">{initial.id && <button type="button" className="button danger" onClick={archive}><Archive size={16} /> Archive</button>}<button className="button" disabled={pending}>{pending ? "Saving…" : "Save product"}</button></div>
  </form>;
}

function updateVariant<K extends keyof VariantForm>(setter: React.Dispatch<React.SetStateAction<VariantForm[]>>, index: number, key: K, value: VariantForm[K]) { setter(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item)); }
function updateOption<K extends keyof OptionForm>(setter: React.Dispatch<React.SetStateAction<OptionForm[]>>, index: number, key: K, value: OptionForm[K]) { setter(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item)); }
