"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import type { CategoryBenefit, CategoryFaq, CategorySection, CategoryStep, CategoryUseCase } from "@/lib/category-content";

export type CategoryEditorInitial = {
  id?: string; name: string; slug: string; shortDescription: string; description: string; icon: string; imageUrl: string;
  cardTitle: string; cardText: string; cardImageUrl: string; cardImageAlt: string; heroEyebrow: string; heroHeadline: string; heroDescription: string; heroImageUrl: string; heroImageAlt: string; secondaryImageUrl: string;
  ctaLabel: string; ctaHref: string; secondaryCtaLabel: string; secondaryCtaHref: string; status: "DRAFT" | "PUBLISHED" | "HIDDEN" | "ARCHIVED"; sortOrder: number;
  showOnHomepage: boolean; showInNavigation: boolean; showInShop: boolean; showLanding: boolean; seoTitle: string; seoDescription: string; ogImageUrl: string; canonicalUrl: string; indexable: boolean;
  finalCtaEyebrow: string; finalCtaHeadline: string; finalCtaDescription: string; finalCtaLabel: string; finalCtaHref: string;
  visualTheme: "CORAL" | "SKY" | "MIDNIGHT" | "VIOLET" | "AMBER"; landingLayout: "EDITORIAL" | "ASSURANCE" | "EXECUTIVE" | "MOMENTUM" | "JOURNEY";
  benefits: CategoryBenefit[]; useCases: CategoryUseCase[]; howItWorks: CategoryStep[]; contentSections: CategorySection[]; faq: CategoryFaq[];
};

const blankBenefit = (order: number): CategoryBenefit => ({ icon: "shield-check", title: "", description: "", order, visible: true });
const blankUseCase = (order: number): CategoryUseCase => ({ icon: "map-pin", title: "", description: "", order, visible: true });
const blankStep = (order: number): CategoryStep => ({ title: "", description: "", imageUrl: "", ctaLabel: "", ctaHref: "", order, visible: true });
const blankSection = (order: number): CategorySection => ({ layout: "IMAGE_LEFT", eyebrow: "", heading: "", copy: "", bulletPoints: [], imageUrl: "", ctaLabel: "", ctaHref: "", order, visible: true });
const blankFaq = (order: number): CategoryFaq => ({ question: "", answer: "", order, enabled: true });

export function CategoryEditor({ initial }: { initial: CategoryEditorInitial }) {
  const router = useRouter();
  const [benefits, setBenefits] = useState(initial.benefits);
  const [useCases, setUseCases] = useState(initial.useCases);
  const [steps, setSteps] = useState(initial.howItWorks);
  const [sections, setSections] = useState(initial.contentSections);
  const [faqs, setFaqs] = useState(initial.faq);
  const [message, setMessage] = useState("");
  const [pending, setPending] = useState(false);

  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget);
    const text = (name: string) => String(form.get(name) ?? "").trim() || null;
    const payload = {
      name: text("name"), slug: text("slug"), shortDescription: text("shortDescription"), description: text("description"), icon: text("icon"), imageUrl: text("imageUrl") ?? "",
      cardTitle: text("cardTitle"), cardText: text("cardText"), cardImageUrl: text("cardImageUrl") ?? "", cardImageAlt: text("cardImageAlt"), heroEyebrow: text("heroEyebrow"), heroHeadline: text("heroHeadline"), heroDescription: text("heroDescription"), heroImageUrl: text("heroImageUrl") ?? "", heroImageAlt: text("heroImageAlt"), secondaryImageUrl: text("secondaryImageUrl") ?? "",
      ctaLabel: text("ctaLabel"), ctaHref: text("ctaHref") ?? "", secondaryCtaLabel: text("secondaryCtaLabel"), secondaryCtaHref: text("secondaryCtaHref") ?? "",
      finalCtaEyebrow: text("finalCtaEyebrow"), finalCtaHeadline: text("finalCtaHeadline"), finalCtaDescription: text("finalCtaDescription"), finalCtaLabel: text("finalCtaLabel"), finalCtaHref: text("finalCtaHref") ?? "",
      visualTheme: form.get("visualTheme"), landingLayout: form.get("landingLayout"),
      status: form.get("status"), sortOrder: Number(form.get("sortOrder")), showOnHomepage: form.get("showOnHomepage") === "on", showInNavigation: form.get("showInNavigation") === "on", showInShop: form.get("showInShop") === "on", showLanding: form.get("showLanding") === "on",
      seoTitle: text("seoTitle"), seoDescription: text("seoDescription"), ogImageUrl: text("ogImageUrl") ?? "", canonicalUrl: text("canonicalUrl") ?? "", indexable: form.get("indexable") === "on",
      benefits: benefits.map((item, order) => ({ ...item, order })), useCases: useCases.map((item, order) => ({ ...item, order })), howItWorks: steps.map((item, order) => ({ ...item, order })), contentSections: sections.map((item, order) => ({ ...item, order })), faq: faqs.map((item, order) => ({ ...item, order })),
    };
    const response = await fetch(initial.id ? `/api/admin/categories/${initial.id}` : "/api/admin/categories", { method: initial.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json().catch(() => ({})); setPending(false);
    if (!response.ok) return setMessage(result.error ?? "Category could not be saved");
    setMessage("Category saved"); if (!initial.id) router.replace(`/admin/categories/${result.category.id}`); else router.refresh();
  }

  return <form className="admin-form" onSubmit={save}>
    <section className="admin-panel"><div className="panel-heading"><div><h2>General</h2><p>Identity, lifecycle and storefront ordering.</p></div></div><div className="field-grid three"><label className="field">Name<input name="name" defaultValue={initial.name} required /></label><label className="field">Slug<input name="slug" defaultValue={initial.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label className="field">Icon key<input name="icon" defaultValue={initial.icon} placeholder="shield-check" /></label><label className="field">Status<select name="status" defaultValue={initial.status}>{["DRAFT","PUBLISHED","HIDDEN","ARCHIVED"].map(value => <option key={value}>{value}</option>)}</select></label><label className="field">Display order<input name="sortOrder" type="number" min="0" defaultValue={initial.sortOrder} required /></label><label className="field">Legacy image URL<input name="imageUrl" type="url" defaultValue={initial.imageUrl} /></label><label className="field">Visual theme<select name="visualTheme" defaultValue={initial.visualTheme}>{["CORAL","SKY","MIDNIGHT","VIOLET","AMBER"].map(value => <option key={value}>{value}</option>)}</select></label><label className="field">Landing composition<select name="landingLayout" defaultValue={initial.landingLayout}>{["EDITORIAL","ASSURANCE","EXECUTIVE","MOMENTUM","JOURNEY"].map(value => <option key={value}>{value}</option>)}</select></label></div><label className="field">Short description<textarea name="shortDescription" defaultValue={initial.shortDescription} maxLength={240} /></label><label className="field">Collection description<textarea name="description" defaultValue={initial.description} maxLength={5000} /></label><p className="field-hint">Theme and composition provide a distinct visual identity without tying business logic to the category name.</p></section>
    <section className="admin-panel"><div className="panel-heading"><div><h2>Homepage card</h2><p>Controls how this category is introduced on the current Store homepage.</p></div></div><div className="field-grid"><label className="field">Card title<input name="cardTitle" defaultValue={initial.cardTitle} /></label><label className="field">Card image URL<input name="cardImageUrl" type="url" defaultValue={initial.cardImageUrl} /></label><label className="field">Card image alt text<input name="cardImageAlt" defaultValue={initial.cardImageAlt} maxLength={160} /></label></div><label className="field">Card text<textarea name="cardText" defaultValue={initial.cardText} maxLength={240} /></label></section>
    <section className="admin-panel"><div className="panel-heading"><div><h2>Landing hero</h2><p>Category-specific story and calls to action.</p></div></div><div className="field-grid"><label className="field">Eyebrow<input name="heroEyebrow" defaultValue={initial.heroEyebrow} /></label><label className="field">Headline<input name="heroHeadline" defaultValue={initial.heroHeadline} /></label><label className="field">Hero image URL<input name="heroImageUrl" type="url" defaultValue={initial.heroImageUrl} /></label><label className="field">Hero image alt text<input name="heroImageAlt" defaultValue={initial.heroImageAlt} maxLength={160} /></label><label className="field">Secondary image URL<input name="secondaryImageUrl" type="url" defaultValue={initial.secondaryImageUrl} /></label><label className="field">Primary CTA label<input name="ctaLabel" defaultValue={initial.ctaLabel} /></label><label className="field">Primary CTA path<input name="ctaHref" defaultValue={initial.ctaHref} placeholder="/shop?category=pet" /></label><label className="field">Secondary CTA label<input name="secondaryCtaLabel" defaultValue={initial.secondaryCtaLabel} /></label><label className="field">Secondary CTA path<input name="secondaryCtaHref" defaultValue={initial.secondaryCtaHref} /></label></div><label className="field">Hero description<textarea name="heroDescription" defaultValue={initial.heroDescription} maxLength={1000} /></label></section>
    <StructuredList title="Benefits" description="Visible category-specific reasons to buy." onAdd={() => setBenefits(items => [...items, blankBenefit(items.length)])}>{benefits.map((item, index) => <EditorRow key={index} onRemove={() => setBenefits(items => items.filter((_, i) => i !== index))}><label className="field">Icon<input value={item.icon} onChange={event => update(setBenefits, index, { icon: event.target.value })} /></label><label className="field">Title<input value={item.title} onChange={event => update(setBenefits, index, { title: event.target.value })} required /></label><label className="field wide">Description<textarea value={item.description} onChange={event => update(setBenefits, index, { description: event.target.value })} required /></label><Visible checked={item.visible} onChange={visible => update(setBenefits, index, { visible })} /></EditorRow>)}</StructuredList>
    <StructuredList title="Use cases" description="Real situations that make this category useful and specific." onAdd={() => setUseCases(items => [...items, blankUseCase(items.length)])}>{useCases.map((item, index) => <EditorRow key={index} onRemove={() => setUseCases(items => items.filter((_, i) => i !== index))}><label className="field">Icon<input value={item.icon} onChange={event => update(setUseCases, index, { icon: event.target.value })} /></label><label className="field">Title<input value={item.title} onChange={event => update(setUseCases, index, { title: event.target.value })} required /></label><label className="field wide">Description<textarea value={item.description} onChange={event => update(setUseCases, index, { description: event.target.value })} required /></label><Visible checked={item.visible} onChange={visible => update(setUseCases, index, { visible })} /></EditorRow>)}</StructuredList>
    <StructuredList title="How it works" description="Ordered steps specific to this category." onAdd={() => setSteps(items => [...items, blankStep(items.length)])}>{steps.map((item, index) => <EditorRow key={index} onRemove={() => setSteps(items => items.filter((_, i) => i !== index))}><label className="field">Title<input value={item.title} onChange={event => update(setSteps, index, { title: event.target.value })} required /></label><label className="field">Image URL<input type="url" value={item.imageUrl ?? ""} onChange={event => update(setSteps, index, { imageUrl: event.target.value })} /></label><label className="field wide">Description<textarea value={item.description} onChange={event => update(setSteps, index, { description: event.target.value })} required /></label><Visible checked={item.visible} onChange={visible => update(setSteps, index, { visible })} /></EditorRow>)}</StructuredList>
    <StructuredList title="Content sections" description="Typed image-and-text blocks; arbitrary HTML is never stored." onAdd={() => setSections(items => [...items, blankSection(items.length)])}>{sections.map((item, index) => <EditorRow key={index} onRemove={() => setSections(items => items.filter((_, i) => i !== index))}><label className="field">Layout<select value={item.layout} onChange={event => update(setSections, index, { layout: event.target.value as CategorySection["layout"] })}><option>IMAGE_LEFT</option><option>IMAGE_RIGHT</option><option>TEXT_ONLY</option></select></label><label className="field">Eyebrow<input value={item.eyebrow ?? ""} onChange={event => update(setSections, index, { eyebrow: event.target.value })} /></label><label className="field">Heading<input value={item.heading} onChange={event => update(setSections, index, { heading: event.target.value })} required /></label><label className="field">Image URL<input type="url" value={item.imageUrl ?? ""} onChange={event => update(setSections, index, { imageUrl: event.target.value })} /></label><label className="field wide">Copy<textarea value={item.copy} onChange={event => update(setSections, index, { copy: event.target.value })} required /></label><label className="field wide">Bullet points, one per line<textarea value={item.bulletPoints.join("\n")} onChange={event => update(setSections, index, { bulletPoints: event.target.value.split("\n").map(value => value.trim()).filter(Boolean) })} /></label><Visible checked={item.visible} onChange={visible => update(setSections, index, { visible })} /></EditorRow>)}</StructuredList>
    <StructuredList title="FAQ" description="Only enabled questions are rendered and eligible for FAQ structured data." onAdd={() => setFaqs(items => [...items, blankFaq(items.length)])}>{faqs.map((item, index) => <EditorRow key={index} onRemove={() => setFaqs(items => items.filter((_, i) => i !== index))}><label className="field">Question<input value={item.question} onChange={event => update(setFaqs, index, { question: event.target.value })} required /></label><label className="field wide">Answer<textarea value={item.answer} onChange={event => update(setFaqs, index, { answer: event.target.value })} required /></label><label className="check-field"><input type="checkbox" checked={item.enabled} onChange={event => update(setFaqs, index, { enabled: event.target.checked })} /><span>Enabled</span></label></EditorRow>)}</StructuredList>
    <section className="admin-panel"><div className="panel-heading"><div><h2>Final call to action</h2><p>Close the category story with a focused route into the filtered Shop.</p></div></div><div className="field-grid"><label className="field">Eyebrow<input name="finalCtaEyebrow" defaultValue={initial.finalCtaEyebrow} /></label><label className="field">Headline<input name="finalCtaHeadline" defaultValue={initial.finalCtaHeadline} /></label><label className="field">Button label<input name="finalCtaLabel" defaultValue={initial.finalCtaLabel} /></label><label className="field">Button path<input name="finalCtaHref" defaultValue={initial.finalCtaHref} placeholder="/shop?category=pet" /></label></div><label className="field">Description<textarea name="finalCtaDescription" defaultValue={initial.finalCtaDescription} maxLength={500} /></label></section>
    <section className="admin-panel"><div className="panel-heading"><div><h2>Visibility</h2><p>These switches affect commerce and discovery only. Existing NFC tags remain operational.</p></div></div><div className="check-row"><Check name="showOnHomepage" label="Homepage" checked={initial.showOnHomepage} /><Check name="showInNavigation" label="Navigation" checked={initial.showInNavigation} /><Check name="showInShop" label="Shop filters" checked={initial.showInShop} /><Check name="showLanding" label="Public landing" checked={initial.showLanding} /></div></section>
    <section className="admin-panel"><div className="panel-heading"><div><h2>SEO</h2><p>Independent controls for the category landing.</p></div></div><div className="field-grid"><label className="field">SEO title<input name="seoTitle" defaultValue={initial.seoTitle} maxLength={70} /></label><label className="field">OG image URL<input name="ogImageUrl" type="url" defaultValue={initial.ogImageUrl} /></label><label className="field">Canonical URL<input name="canonicalUrl" type="url" defaultValue={initial.canonicalUrl} /></label></div><label className="field">Meta description<textarea name="seoDescription" defaultValue={initial.seoDescription} maxLength={170} /></label><Check name="indexable" label="Allow search engines to index this landing" checked={initial.indexable} /></section>
    {message && <div className={message === "Category saved" ? "notice" : "form-error"} role="status">{message}</div>}<div className="admin-form-actions"><button className="button" disabled={pending}>{pending ? "Saving…" : "Save category"}</button></div>
  </form>;
}

function StructuredList({ title, description, onAdd, children }: { title: string; description: string; onAdd: () => void; children: React.ReactNode }) { return <section className="admin-panel"><div className="panel-heading"><div><h2>{title}</h2><p>{description}</p></div><button className="button secondary" type="button" onClick={onAdd}><Plus size={16} /> Add item</button></div><div className="admin-stack">{children}</div></section>; }
function EditorRow({ onRemove, children }: { onRemove: () => void; children: React.ReactNode }) { return <div className="variant-editor structured-editor">{children}<button className="text-button danger-text" type="button" onClick={onRemove}><Trash2 size={15} /> Remove</button></div>; }
function Check({ name, label, checked }: { name: string; label: string; checked: boolean }) { return <label className="check-field"><input type="checkbox" name={name} defaultChecked={checked} /><span>{label}</span></label>; }
function Visible({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <label className="check-field"><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} /><span>Visible</span></label>; }
function update<T>(setter: React.Dispatch<React.SetStateAction<T[]>>, index: number, changes: Partial<T>) { setter(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item)); }
