"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type ListingDefaults = { taxonomyId?: string; shippingProfileId?: string; readinessStateId?: string; whoMade?: "i_did" | "collective" | "someone_else"; whenMade?: string; isSupply?: boolean; shouldAutoRenew?: boolean };
type Connection = { status: string; shopName: string | null; shopId: string | null; syncEnabled: boolean; listingDefaults: ListingDefaults; lastError: string | null; lastSyncedAt: string | null; lastOrderSyncedAt: string | null; listings: Array<{ id: string; productId: string; productName: string; externalId: string; externalUrl: string | null; state: string | null; lastSyncedAt: string | null; lastError: string | null }> };
type Product = { id: string; name: string; variants: Array<{ sku: string; available: number; active: boolean }> };
type Job = { id: string; type: string; status: string; attempts: number; lastError: string | null; productName: string; updatedAt: string };

export function EtsyManager({ configured, canManage, callbackUrl, result, connection, products, jobs }: { configured: boolean; canManage: boolean; callbackUrl: string; result: string | null; connection: Connection | null; products: Product[]; jobs: Job[] }) {
  const router = useRouter();
  const [message, setMessage] = useState(RESULTS[result ?? ""] ?? "");
  const [busy, setBusy] = useState(false);
  const linked = new Set(connection?.listings.map(listing => listing.productId) ?? []);
  const linkable = useMemo(() => products.filter(product => !linked.has(product.id)), [products, linked]);
  async function api(path: string, init: RequestInit, success = "Saved.") {
    setBusy(true); setMessage("");
    try { const response = await fetch(path, init); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? "Etsy request failed"); setMessage(body.processed != null ? `Sync complete: ${body.succeeded} processed, ${body.failed} need attention.` : success); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Etsy request failed"); }
    finally { setBusy(false); }
  }
  function saveSettings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void api("/api/admin/etsy/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ syncEnabled: form.get("syncEnabled") === "on", listingDefaults: { taxonomyId: form.get("taxonomyId"), shippingProfileId: form.get("shippingProfileId"), readinessStateId: form.get("readinessStateId"), whoMade: form.get("whoMade"), whenMade: form.get("whenMade"), isSupply: form.get("isSupply") === "on", shouldAutoRenew: form.get("shouldAutoRenew") === "on" } }) }, "Etsy publishing defaults saved."); }
  function createReadiness(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void api("/api/admin/etsy/readiness", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ readinessState: form.get("readinessState"), minProcessingTime: Number(form.get("minProcessingTime")), maxProcessingTime: Number(form.get("maxProcessingTime")), processingTimeUnit: form.get("processingTimeUnit") }) }, "Etsy processing profile created and selected."); }
  function createDraft(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const publish = form.get("publish") === "on"; if (!window.confirm(publish ? "Publish this product immediately on Etsy? Make sure its pricing, shipping profile and images are final." : "Create this Etsy listing as a draft?")) return; void api("/api/admin/etsy/listings/draft", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productId: form.get("productId"), publish }) }, publish ? "Etsy listing published." : "Etsy draft created and linked."); }
  function link(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void api("/api/admin/etsy/listings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productId: form.get("productId"), externalId: form.get("externalId") }) }, "Etsy listing linked."); }
  const heading = <div className="admin-heading"><div><p className="admin-kicker">Sales channels</p><h1>Etsy</h1><p>Create, publish and synchronise Etsy listings from your Tapkin products. Tapkin remains the source of truth for stock and variants.</p></div>{connection && canManage ? <button className="button secondary" disabled={busy} onClick={() => void api("/api/admin/etsy/sync", { method: "POST" })}>Sync now</button> : null}</div>;
  if (!configured) return <div>{heading}<section className="admin-panel"><h2>Configure the Etsy app first</h2><p>Add <code>ETSY_API_KEY</code> and <code>ETSY_SHARED_SECRET</code> to this deployment, then register this exact callback URL in Etsy:</p><code>{callbackUrl}</code><p className="muted">For automatic background sync also set <code>ETSY_SYNC_SECRET</code>. Credentials are server-only.</p></section></div>;
  if (!connection) return <div>{heading}{message && <p className="form-message">{message}</p>}<section className="admin-panel"><h2>Connect your Etsy shop</h2><p>Authorise the Etsy seller account for this store. Reconnect once after this update so Etsy grants the shop permission used to create processing profiles.</p>{canManage ? <a className="button" href="/api/admin/etsy/connect">Connect Etsy</a> : <p className="muted">A store administrator must connect Etsy.</p>}</section></div>;
  const defaults = connection.listingDefaults ?? {};
  return <div>{heading}{message && <p className="form-message">{message}</p>}
    <section className="admin-panel"><div className="panel-heading"><div><h2>{connection.shopName || "Connected Etsy shop"}</h2><p>Shop ID {connection.shopId} · {connection.status.toLowerCase()}</p></div></div>{connection.lastError ? <p className="form-error">Latest sync: {connection.lastError}</p> : <p className="muted">Stock last sent: {connection.lastSyncedAt ? new Date(connection.lastSyncedAt).toLocaleString("en-AU") : "not yet"} · paid Etsy orders last checked: {connection.lastOrderSyncedAt ? new Date(connection.lastOrderSyncedAt).toLocaleString("en-AU") : "not yet"}</p>}<form className="admin-form" onSubmit={saveSettings}><label className="checkbox-row"><input name="syncEnabled" type="checkbox" defaultChecked={connection.syncEnabled} disabled={!canManage} /> Automatically synchronise linked stock and import paid Etsy orders</label><h3>Defaults for new physical listings</h3><p className="muted">Copy the numeric IDs from Etsy once for this shop. They are mandatory for a physical listing.</p><div className="field-grid three"><label className="field">Etsy taxonomy ID<input name="taxonomyId" inputMode="numeric" pattern="[0-9]+" defaultValue={defaults.taxonomyId ?? ""} required disabled={!canManage} /></label><label className="field">Shipping profile ID<input name="shippingProfileId" inputMode="numeric" pattern="[0-9]+" defaultValue={defaults.shippingProfileId ?? ""} required disabled={!canManage} /></label><label className="field">Processing profile ID<input name="readinessStateId" inputMode="numeric" pattern="[0-9]+" defaultValue={defaults.readinessStateId ?? ""} required disabled={!canManage} /></label><label className="field">Who made it?<select name="whoMade" defaultValue={defaults.whoMade ?? "i_did"} disabled={!canManage}><option value="i_did">I did</option><option value="collective">A member of my shop</option><option value="someone_else">Someone else</option></select></label><label className="field">When made?<input name="whenMade" defaultValue={defaults.whenMade ?? "made_to_order"} required disabled={!canManage} /><small>Use Etsy’s accepted value for your listing type.</small></label></div><div className="check-row"><label className="check-field"><input name="isSupply" type="checkbox" defaultChecked={Boolean(defaults.isSupply)} disabled={!canManage} /><span>This is a craft supply</span></label><label className="check-field"><input name="shouldAutoRenew" type="checkbox" defaultChecked={defaults.shouldAutoRenew !== false} disabled={!canManage} /><span>Auto-renew listing</span></label></div>{canManage && <button className="button" disabled={busy}>Save Etsy defaults</button>}</form></section>
    <section className="admin-panel"><h2>Create a processing profile</h2><p className="muted">For printed tags, choose Made to order and your real processing range. The resulting Etsy profile is saved above automatically.</p><form className="admin-form inline-form" onSubmit={createReadiness}><label>Fulfilment<select name="readinessState" defaultValue="made_to_order" disabled={!canManage}><option value="made_to_order">Made to order</option><option value="ready_to_ship">Ready to ship</option></select></label><label>Minimum<input name="minProcessingTime" type="number" min="1" defaultValue="3" disabled={!canManage} /></label><label>Maximum<input name="maxProcessingTime" type="number" min="1" defaultValue="7" disabled={!canManage} /></label><label>Unit<select name="processingTimeUnit" defaultValue="days" disabled={!canManage}><option value="days">Days</option><option value="weeks">Weeks</option></select></label>{canManage && <button className="button secondary" disabled={busy}>Create profile</button>}</form></section>
    <section className="admin-panel"><h2>Create from Tapkin</h2><p className="muted">Creates an Etsy draft with product title, description, images, SKU stock, price and up to three customer variations: Colour, Size and Style. Publishing is an explicit choice.</p>{canManage && linkable.length ? <form className="admin-form inline-form" onSubmit={createDraft}><label>Tapkin product<select name="productId" required>{linkable.map(product => <option value={product.id} key={product.id}>{product.name} · {product.variants.filter(variant => variant.active).map(variant => `${variant.sku} (${variant.available})`).join(", ")}</option>)}</select></label><label className="check-field"><input name="publish" type="checkbox" /><span>Publish after Etsy accepts images and variations</span></label><button className="button" disabled={busy}>Create Etsy listing</button></form> : <p className="admin-empty">{linkable.length ? "A store administrator can create listings." : "Every available product is already linked."}</p>}</section>
    <section className="admin-panel"><h2>Link an existing listing</h2><p className="muted">Use this only for a listing that was created in Etsy. Every active Tapkin SKU must exist exactly once in that listing.</p>{canManage && linkable.length ? <form className="admin-form inline-form" onSubmit={link}><label>Tapkin product<select name="productId" required>{linkable.map(product => <option value={product.id} key={product.id}>{product.name} · {product.variants.map(variant => `${variant.sku} (${variant.available})`).join(", ")}</option>)}</select></label><label>Etsy listing ID<input name="externalId" inputMode="numeric" pattern="[0-9]+" required placeholder="e.g. 1234567890" /></label><button className="button secondary" disabled={busy}>Verify and link</button></form> : <p className="admin-empty">{linkable.length ? "A store administrator can link listings." : "Every available product is already linked."}</p>}</section>
    <section className="admin-panel"><h2>Linked listings</h2>{connection.listings.length ? <div className="admin-table"><div className="admin-tr admin-th"><span>Product</span><span>Etsy listing</span><span>State</span><span>Last sync</span><span>Action</span></div>{connection.listings.map(listing => <div className="admin-tr" key={listing.id}><span><strong>{listing.productName}</strong>{listing.lastError && <small className="form-error">{listing.lastError}</small>}</span><span>{listing.externalUrl ? <a href={listing.externalUrl} target="_blank" rel="noreferrer">#{listing.externalId}</a> : `#${listing.externalId}`}</span><span>{listing.state ?? "—"}</span><span>{listing.lastSyncedAt ? new Date(listing.lastSyncedAt).toLocaleString("en-AU") : "Queued"}</span><span>{canManage ? <button className="text-button" disabled={busy} onClick={() => void api(`/api/admin/etsy/listings?productId=${listing.productId}`, { method: "DELETE" }, "Etsy listing unlinked.")}>Unlink</button> : "—"}</span></div>)}</div> : <p className="admin-empty">No Etsy listings are linked.</p>}</section>
    <section className="admin-panel"><h2>Sync activity</h2>{jobs.length ? <div className="admin-table"><div className="admin-tr admin-th"><span>Task</span><span>Status</span><span>Attempts</span><span>Updated</span></div>{jobs.map(job => <div className="admin-tr" key={job.id}><span><strong>{job.type === "RECEIPTS" ? "Import paid Etsy orders" : job.productName}</strong>{job.lastError && <small className="form-error">{job.lastError}</small>}</span><span>{job.status}</span><span>{job.attempts}</span><span>{new Date(job.updatedAt).toLocaleString("en-AU")}</span></div>)}</div> : <p className="admin-empty">No Etsy sync jobs yet.</p>}</section>
  </div>;
}

const RESULTS: Record<string, string> = { connected: "Etsy has been connected.", declined: "Etsy authorisation was cancelled.", invalid: "The Etsy connection could not be verified. Start again.", "no-shop": "That Etsy account does not have a shop to connect.", failed: "Etsy could not complete the connection. Check the app callback URL and try again.", config: "Etsy credentials have not been configured on this deployment." };
