import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, PackageCheck, Palette, Printer, QrCode, Radio } from "lucide-react";
import { CategoryIcon } from "@/components/category-icon";
import { parseLandingContent } from "@/lib/landing-sections";
import type { PublicCategory } from "@/lib/category-query";

type Item = { icon: string; title: string; description: string; imageUrl: string; imageAlt: string; ctaLabel: string; ctaHref: string };

export function LandingSectionRenderer({ category, store }: { category: PublicCategory; store: { displayName: string; currency: string; nfcEnabled: boolean } }) {
  const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: store.currency });
  const shopHref = `/shop?category=${category.slug}`;
  return <section className="category-landing modular-landing" data-theme={category.visualTheme.toLowerCase()}><nav className="breadcrumbs category-breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/shop">Shop</Link><span>/</span><span>{category.name}</span></nav>{category.landingSections.map(section => {
    const value = parseLandingContent(section.type, section.content); if (!value) return null;
    const headline = text(value.headline); const copy = text(value.copy); const eyebrow = text(value.eyebrow); const imageUrl = text(value.imageUrl); const imageAlt = text(value.imageAlt); const ctaLabel = text(value.ctaLabel); const ctaHref = text(value.ctaHref) || shopHref;
    if (section.type === "HERO") return <section className="category-landing-hero" key={section.id}><div className="category-hero-copy">{eyebrow && <span className="eyebrow"><CategoryIcon name={category.icon} size={15} /> {eyebrow}</span>}<h1>{headline || category.heroHeadline || category.name}</h1><p className="lead">{copy || category.heroDescription || category.description}</p>{ctaLabel && <div className="actions"><Link className="button category-primary" href={ctaHref}>{ctaLabel} <ArrowRight size={17} /></Link></div>}<div className="category-hero-trust">{store.nfcEnabled ? <><span><Radio size={16} /> NFC</span><span><QrCode size={16} /> QR</span><span><Check size={16} /> No app needed</span></> : <><span><Printer size={16} /> 3D printed</span><span><Palette size={16} /> Configurable</span><span><PackageCheck size={16} /> Small batch</span></>}</div></div>{imageUrl ? <Image src={imageUrl} alt={imageAlt || `${category.name} products`} width={900} height={720} priority unoptimized /> : <div className="category-hero-placeholder" role="img" aria-label={`${category.name} visual placeholder`}><div className="smart-object"><CategoryIcon name={category.icon} size={62} /><strong>{category.name}</strong><small>{store.displayName}</small></div></div>}</section>;
    if (["BENEFITS", "FEATURE_BADGES", "FEATURE_LIST", "TRUST_STRIP", "STATS", "STORY_PROCESS", "STEPS"].includes(section.type)) { const items = array<Item>(value.items); return <section className={`category-benefits modular-${section.type.toLowerCase().replaceAll("_", "-")}`} key={section.id}><Heading eyebrow={eyebrow} headline={headline || section.name} copy={copy} /><div className={section.type === "STEPS" ? "step-grid" : "benefit-grid"}>{items.map((item, index) => <article key={`${item.title}-${index}`}>{section.type === "STEPS" ? <span className="step-number">{index + 1}</span> : <span className="icon"><CategoryIcon name={item.icon} /></span>}{item.imageUrl && <Image src={item.imageUrl} alt={item.imageAlt} width={560} height={380} unoptimized />}<h3>{item.title}</h3><p>{item.description}</p>{item.ctaLabel && item.ctaHref && <Link href={item.ctaHref}>{item.ctaLabel} <ArrowRight size={15} /></Link>}</article>)}</div></section>; }
    if (["PRODUCT_SHOWCASE", "PRODUCT_GRID"].includes(section.type)) { const limit = typeof value.limit === "number" ? value.limit : 6; const products = category.products.filter(product => !value.featuredOnly || product.featured).slice(0, limit); return <section className="category-products" key={section.id}><Heading eyebrow={eyebrow} headline={headline || section.name} copy={copy} /><div className="shop-grid">{products.map(product => <article className="card product-card" key={product.id}>{product.images[0] ? <Image className="category-product-image" src={product.images[0].url} alt={product.images[0].altText} width={500} height={500} unoptimized /> : <div className="category-product-placeholder"><CategoryIcon name={category.icon} /><span>Made to order</span></div>}<h3>{product.name}</h3><p>{product.shortDescription ?? product.description}</p>{product.variants[0] && <strong className="price">From {money.format(product.variants[0].priceCents / 100)}</strong>}<Link className="button" href={`/products/${product.slug}`}>View product</Link></article>)}</div><Link className="category-shop-link" href={shopHref}>View the full filtered collection <ArrowRight size={17} /></Link></section>; }
    if (section.type === "CATEGORY_GRID") return null;
    if (section.type === "FAQ") { const items = array<{ question: string; answer: string }>(value.items); return <section className="faq-section category-faq" key={section.id}><Heading eyebrow={eyebrow} headline={headline || section.name} copy={copy} />{items.map(item => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>; }
    if (section.type === "CTA_BANNER") return <section className="category-final-cta" key={section.id}>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{headline}</h2>{copy && <p>{copy}</p>}{ctaLabel && <Link className="button category-primary" href={ctaHref}>{ctaLabel} <ArrowRight size={17} /></Link>}</section>;
    const bullets = array<string>(value.bullets); const layout = text(value.layout, "IMAGE_RIGHT").toLowerCase().replaceAll("_", "-");
    return <section className={`category-story ${layout}`} key={section.id}><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{headline || section.name}</h2>{copy && <p>{copy}</p>}{bullets.length > 0 && <ul>{bullets.map(item => <li key={item}><Check size={18} />{item}</li>)}</ul>}{ctaLabel && <Link className="button secondary" href={ctaHref}>{ctaLabel}</Link>}</div>{imageUrl && !layout.includes("text-only") && <Image src={imageUrl} alt={imageAlt} width={760} height={600} unoptimized />}</section>;
  })}</section>;
}

function Heading({ eyebrow, headline, copy }: { eyebrow: string; headline: string; copy: string }) { return <div className="section-head">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{headline}</h2>{copy && <p>{copy}</p>}</div>; }
function text(value: unknown, fallback = "") { return typeof value === "string" ? value : fallback; }
function array<T>(value: unknown) { return Array.isArray(value) ? value as T[] : []; }
