"use client";

import { useRef, useState } from "react";
import { ChevronDown, ChevronUp, Copy, Eye, EyeOff, Plus, Trash2 } from "lucide-react";
import type { LandingSectionType } from "@prisma/client";
import { CategoryImageUploadField } from "@/components/category-image-upload-field";
import { ColourField } from "@/components/colour-field";
import { blankLandingSection, landingSectionRegistry, landingSectionTypes, type LandingSectionDraft } from "@/lib/landing-sections";

const itemTypes = new Set<LandingSectionType>(["FEATURE_BADGES", "BENEFITS", "STEPS", "FEATURE_LIST", "STORY_PROCESS", "TRUST_STRIP", "STATS"]);
const narrativeTypes = new Set<LandingSectionType>(["HERO", "MEDIA_CONTENT", "CTA_BANNER", "RICH_TEXT"]);
const gridTypes = new Set<LandingSectionType>(["PRODUCT_SHOWCASE", "PRODUCT_GRID", "CATEGORY_GRID"]);
type SectionItem = { icon?: string; title?: string; description?: string; supportingText?: string; imageUrl?: string; imageAlt?: string; ctaLabel?: string; ctaHref?: string; backgroundColour?: string; iconBackgroundColour?: string; iconColour?: string; imagePosition?: number; visible?: boolean; order?: number };
type FaqItem = { question?: string; answer?: string; visible?: boolean; order?: number };
type TextBlock = { type: "EYEBROW" | "HEADING" | "SUBHEADING" | "PARAGRAPH" | "SUPPORTING_TEXT"; text: string; visible: boolean; order: number };
type FeatureItem = { icon: string; label: string; supportingText: string; backgroundColour: string; iconColour: string; visible: boolean; order: number };
const blankItem = (): SectionItem => ({ icon: "sparkles", title: "", description: "", supportingText: "", imageUrl: "", imageAlt: "", ctaLabel: "", ctaHref: "", backgroundColour: "", iconBackgroundColour: "", iconColour: "", imagePosition: 0, visible: true, order: 0 });

export function LandingSectionEditor({ categoryId, initial, endpoint }: { categoryId?: string; initial: LandingSectionDraft[]; endpoint?: string }) {
  const listRef = useRef<HTMLDivElement>(null);
  const [sections, setSections] = useState(initial);
  const [addType, setAddType] = useState<LandingSectionType>("MEDIA_CONTENT");
  const [pending, setPending] = useState(false);
  const [message, setMessage] = useState("");
  const update = (index: number, changes: Partial<LandingSectionDraft>) => setSections(rows => rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...changes } : row));
  const content = (index: number, changes: Record<string, unknown>) => update(index, { content: { ...sections[index].content, ...changes } });
  const move = (index: number, delta: number) => setSections(rows => { const target = index + delta; if (target < 0 || target >= rows.length) return rows; const next = [...rows]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  async function save() {
    if (!endpoint && !categoryId) return;
    setPending(true); setMessage("");
    const response = await fetch(endpoint ?? `/api/admin/categories/${categoryId}/sections`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ sections }) });
    const result = await response.json().catch(() => ({})); setPending(false);
    setMessage(response.ok ? "Landing sections saved" : result.error ?? "Landing sections could not be saved");
  }
  function addSection() {
    setSections(rows => [...rows, blankLandingSection(addType)]);
    setMessage("Section added. Save sections to publish this change.");
    requestAnimationFrame(() => listRef.current?.lastElementChild?.scrollIntoView({ behavior: "smooth", block: "center" }));
  }
  const groups = ["Hero", "Content", "Features", "Process", "Commerce", "Conversion"] as const;
  return <section className="admin-panel landing-builder">
    <div className="panel-heading"><div><h2>Sections</h2><p>Add, edit, hide, reorder, duplicate or remove structured modules. Public pages never accept arbitrary HTML, CSS or JavaScript.</p></div><button className="button" type="button" disabled={pending} onClick={save}>{pending ? "Saving…" : "Save sections"}</button></div>
    <div className="landing-builder-add"><select aria-label="Section type" value={addType} onChange={event => setAddType(event.target.value as LandingSectionType)}>{groups.map(group => <optgroup label={group} key={group}>{landingSectionTypes.filter(type => landingSectionRegistry[type].group === group).map(type => <option key={type} value={type}>{landingSectionRegistry[type].label}</option>)}</optgroup>)}</select><span>{landingSectionRegistry[addType].description}</span><button className="button secondary" type="button" disabled={pending} onClick={addSection}><Plus size={16} /> Add section</button></div>
    <div className="landing-builder-list" ref={listRef}>{sections.map((section, index) => <article className={`landing-builder-section${section.visible ? "" : " is-hidden"}`} key={`${section.id ?? section.type}-${index}`}>
      <header><strong>{index + 1}. {section.name}</strong><span>{landingSectionRegistry[section.type].label}</span><div><button type="button" aria-label="Move up" onClick={() => move(index, -1)} disabled={index === 0}><ChevronUp size={16} /></button><button type="button" aria-label="Move down" onClick={() => move(index, 1)} disabled={index === sections.length - 1}><ChevronDown size={16} /></button><button type="button" aria-label={section.visible ? "Hide section" : "Show section"} onClick={() => update(index, { visible: !section.visible })}>{section.visible ? <Eye size={16} /> : <EyeOff size={16} />}</button><button type="button" aria-label="Duplicate section" onClick={() => setSections(rows => [...rows.slice(0, index + 1), { ...section, id: undefined, name: `${section.name} copy`, content: structuredClone(section.content) }, ...rows.slice(index + 1)])}><Copy size={16} /></button><button type="button" aria-label="Delete section" onClick={() => setSections(rows => rows.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={16} /></button></div></header>
      <div className="field-grid"><label className="field">Admin name<input value={section.name} maxLength={100} onChange={event => update(index, { name: event.target.value })} /></label><label className="field">Type<select value={section.type} onChange={event => { const type = event.target.value as LandingSectionType; update(index, blankLandingSection(type)); }}>{landingSectionTypes.map(type => <option key={type} value={type}>{landingSectionRegistry[type].label}</option>)}</select></label></div>
      <CommonCopy section={section} onChange={changes => content(index, changes)} />
      <SectionStyle section={section} onChange={changes => content(index, changes)} />
      {narrativeTypes.has(section.type) && <NarrativeFields categoryId={categoryId} section={section} onChange={changes => content(index, changes)} />}
      {gridTypes.has(section.type) && <div className="field-grid"><label className="field">Maximum items<input type="number" min="1" max="24" value={number(section.content.limit, 6)} onChange={event => content(index, { limit: Number(event.target.value) })} /></label><label className="check-field"><input type="checkbox" checked={Boolean(section.content.featuredOnly)} onChange={event => content(index, { featuredOnly: event.target.checked })} /><span>Featured only</span></label></div>}
      {itemTypes.has(section.type) && <ItemsEditor categoryId={categoryId} sectionType={section.type} items={array<SectionItem>(section.content.items)} onChange={items => content(index, { items })} />}
      {section.type === "FAQ" && <FaqEditor items={array<FaqItem>(section.content.items)} onChange={items => content(index, { items })} />}
    </article>)}</div>
    {!sections.length && <div className="admin-empty">No sections yet. Add the first module to build this page.</div>}
    {message && <div className={message === "Landing sections saved" || message.startsWith("Section added") ? "notice" : "form-error"} role="status">{message}</div>}
  </section>;
}

function CommonCopy({ section, onChange }: { section: LandingSectionDraft; onChange: (changes: Record<string, unknown>) => void }) { return <div className="field-grid"><label className="field">Eyebrow<input value={string(section.content.eyebrow)} maxLength={100} onChange={event => onChange({ eyebrow: event.target.value })} /></label><label className="field">Headline<input value={string(section.content.headline)} maxLength={180} onChange={event => onChange({ headline: event.target.value })} /></label><label className="field wide">Copy<textarea value={string(section.content.copy)} maxLength={3000} onChange={event => onChange({ copy: event.target.value })} /></label></div>; }
function SectionStyle({ section, onChange }: { section: LandingSectionDraft; onChange: (changes: Record<string, unknown>) => void }) { return <details className="admin-subpanel"><summary>Style and colours</summary><div className="field-grid"><ColourField label="Section background" value={string(section.content.backgroundColour)} onChange={backgroundColour => onChange({ backgroundColour })} /><ColourField label="Text colour" value={string(section.content.textColour)} onChange={textColour => onChange({ textColour })} /><label className="field">Corner radius<select value={string(section.content.radius, "LARGE")} onChange={event => onChange({ radius: event.target.value })}>{["SMALL", "MEDIUM", "LARGE", "EXTRA_LARGE"].map(value => <option key={value}>{value}</option>)}</select></label></div></details>; }

function NarrativeFields({ categoryId, section, onChange }: { categoryId?: string; section: LandingSectionDraft; onChange: (changes: Record<string, unknown>) => void }) {
  const textBlocks = array<TextBlock>(section.content.textBlocks); const features = array<FeatureItem>(section.content.features);
  return <><div className="field-grid"><label className="field">Layout<select value={string(section.content.layout, "IMAGE_RIGHT")} onChange={event => onChange({ layout: event.target.value })}>{["IMAGE_LEFT", "IMAGE_RIGHT", "TEXT_ONLY", "CENTRED"].map(value => <option key={value}>{value}</option>)}</select></label><CategoryImageUploadField categoryId={categoryId} label="Section image" value={string(section.content.imageUrl)} onChange={imageUrl => onChange({ imageUrl })} /><label className="field">Image alt text<input value={string(section.content.imageAlt)} onChange={event => onChange({ imageAlt: event.target.value })} /></label>{section.type === "CTA_BANNER" && <CategoryImageUploadField categoryId={categoryId} label="Mobile image" value={string(section.content.mobileImageUrl)} onChange={mobileImageUrl => onChange({ mobileImageUrl })} />}</div>
    {section.type === "HERO" && <CollectionEditor title="Additional text blocks" onAdd={() => onChange({ textBlocks: [...textBlocks, { type: "PARAGRAPH", text: "", visible: true, order: textBlocks.length }] })}>{textBlocks.map((block, index) => <div className="variant-editor" key={index}><label className="field">Text type<select value={block.type} onChange={event => onChange({ textBlocks: replace(textBlocks, index, { type: event.target.value as TextBlock["type"] }) })}>{["EYEBROW", "HEADING", "SUBHEADING", "PARAGRAPH", "SUPPORTING_TEXT"].map(value => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className="field wide">Text<textarea value={block.text} onChange={event => onChange({ textBlocks: replace(textBlocks, index, { text: event.target.value }) })} /></label><RowActions visible={block.visible} index={index} length={textBlocks.length} onVisible={visible => onChange({ textBlocks: replace(textBlocks, index, { visible }) })} onMove={delta => onChange({ textBlocks: moveRow(textBlocks, index, delta) })} onDelete={() => onChange({ textBlocks: removeRow(textBlocks, index) })} /></div>)}</CollectionEditor>}
    {section.type === "HERO" && <CollectionEditor title="Hero icon features" onAdd={() => onChange({ features: [...features, { icon: "sparkles", label: "", supportingText: "", backgroundColour: "#dff3fa", iconColour: "#17212b", visible: true, order: features.length }] })}>{features.map((feature, index) => <div className="variant-editor" key={index}><label className="field">Icon<input value={feature.icon} onChange={event => onChange({ features: replace(features, index, { icon: event.target.value }) })} /></label><label className="field">Label<input value={feature.label} onChange={event => onChange({ features: replace(features, index, { label: event.target.value }) })} /></label><label className="field">Supporting text<input value={feature.supportingText} onChange={event => onChange({ features: replace(features, index, { supportingText: event.target.value }) })} /></label><ColourField label="Circle colour" value={feature.backgroundColour} onChange={backgroundColour => onChange({ features: replace(features, index, { backgroundColour }) })} /><ColourField label="Icon colour" value={feature.iconColour} onChange={iconColour => onChange({ features: replace(features, index, { iconColour }) })} /><RowActions visible={feature.visible} index={index} length={features.length} onVisible={visible => onChange({ features: replace(features, index, { visible }) })} onMove={delta => onChange({ features: moveRow(features, index, delta) })} onDelete={() => onChange({ features: removeRow(features, index) })} /></div>)}</CollectionEditor>}
    <CtaFields section={section} onChange={onChange} /><label className="field wide">Bullets, one per line<textarea value={array<string>(section.content.bullets).join("\n")} onChange={event => onChange({ bullets: event.target.value.split("\n").map(value => value.trim()).filter(Boolean) })} /></label></>;
}

function CtaFields({ section, onChange }: { section: LandingSectionDraft; onChange: (changes: Record<string, unknown>) => void }) { return <details className="admin-subpanel" open><summary>Buttons</summary><div className="field-grid"><label className="field">Primary label<input value={string(section.content.ctaLabel)} onChange={event => onChange({ ctaLabel: event.target.value })} /></label><label className="field">Primary destination<input value={string(section.content.ctaHref)} placeholder="/shop or https://…" onChange={event => onChange({ ctaHref: event.target.value })} /></label><ColourField label="Primary background" value={string(section.content.ctaBackground)} onChange={ctaBackground => onChange({ ctaBackground })} /><ColourField label="Primary text" value={string(section.content.ctaTextColour)} onChange={ctaTextColour => onChange({ ctaTextColour })} /><ColourField label="Primary border" value={string(section.content.ctaBorderColour)} onChange={ctaBorderColour => onChange({ ctaBorderColour })} /><label className="check-field"><input type="checkbox" checked={section.content.ctaVisible !== false} onChange={event => onChange({ ctaVisible: event.target.checked })} /><span>Show primary button</span></label><label className="field">Secondary label<input value={string(section.content.secondaryCtaLabel)} onChange={event => onChange({ secondaryCtaLabel: event.target.value })} /></label><label className="field">Secondary destination<input value={string(section.content.secondaryCtaHref)} placeholder="/activate or https://…" onChange={event => onChange({ secondaryCtaHref: event.target.value })} /></label><ColourField label="Secondary background" value={string(section.content.secondaryCtaBackground)} onChange={secondaryCtaBackground => onChange({ secondaryCtaBackground })} /><ColourField label="Secondary text" value={string(section.content.secondaryCtaTextColour)} onChange={secondaryCtaTextColour => onChange({ secondaryCtaTextColour })} /><ColourField label="Secondary border" value={string(section.content.secondaryCtaBorderColour)} onChange={secondaryCtaBorderColour => onChange({ secondaryCtaBorderColour })} /><label className="check-field"><input type="checkbox" checked={section.content.secondaryCtaVisible !== false} onChange={event => onChange({ secondaryCtaVisible: event.target.checked })} /><span>Show secondary button</span></label></div></details>; }

function ItemsEditor({ categoryId, sectionType, items, onChange }: { categoryId?: string; sectionType: LandingSectionType; items: SectionItem[]; onChange: (items: SectionItem[]) => void }) { const update = (index: number, changes: Partial<SectionItem>) => onChange(replace(items, index, changes)); return <CollectionEditor title={sectionType === "STEPS" ? "Steps" : sectionType === "STORY_PROCESS" ? "Story items" : "Items"} onAdd={() => onChange([...items, { ...blankItem(), order: items.length }])}>{items.map((item, index) => <div className="variant-editor" key={index}><label className="field">Icon<input value={item.icon ?? "sparkles"} onChange={event => update(index, { icon: event.target.value })} /></label><label className="field">Title<input value={item.title ?? ""} onChange={event => update(index, { title: event.target.value })} /></label><label className="field wide">Description<textarea value={item.description ?? ""} onChange={event => update(index, { description: event.target.value })} /></label><CategoryImageUploadField categoryId={categoryId} label="Item image" value={item.imageUrl ?? ""} onChange={imageUrl => update(index, { imageUrl })} /><label className="field">Image alt text<input value={item.imageAlt ?? ""} onChange={event => update(index, { imageAlt: event.target.value })} /></label><ColourField label={sectionType === "STEPS" ? "Card background" : "Item background"} value={item.backgroundColour ?? ""} onChange={backgroundColour => update(index, { backgroundColour })} /><ColourField label="Icon background" value={item.iconBackgroundColour ?? ""} onChange={iconBackgroundColour => update(index, { iconBackgroundColour })} /><ColourField label="Icon colour" value={item.iconColour ?? ""} onChange={iconColour => update(index, { iconColour })} /><label className="field">CTA label<input value={item.ctaLabel ?? ""} onChange={event => update(index, { ctaLabel: event.target.value })} /></label><label className="field">CTA destination<input value={item.ctaHref ?? ""} placeholder="/shop" onChange={event => update(index, { ctaHref: event.target.value })} /></label><RowActions visible={item.visible !== false} index={index} length={items.length} onVisible={visible => update(index, { visible })} onMove={delta => onChange(moveRow(items, index, delta))} onDelete={() => onChange(removeRow(items, index))} /></div>)}</CollectionEditor>; }
function FaqEditor({ items, onChange }: { items: FaqItem[]; onChange: (items: FaqItem[]) => void }) { const update = (index: number, changes: Partial<FaqItem>) => onChange(replace(items, index, changes)); return <CollectionEditor title="Questions" onAdd={() => onChange([...items, { question: "", answer: "", visible: true, order: items.length }])}>{items.map((item, index) => <div className="variant-editor" key={index}><label className="field">Question<input value={item.question ?? ""} onChange={event => update(index, { question: event.target.value })} /></label><label className="field wide">Answer<textarea value={item.answer ?? ""} onChange={event => update(index, { answer: event.target.value })} /></label><RowActions visible={item.visible !== false} index={index} length={items.length} onVisible={visible => update(index, { visible })} onMove={delta => onChange(moveRow(items, index, delta))} onDelete={() => onChange(removeRow(items, index))} /></div>)}</CollectionEditor>; }
function CollectionEditor({ title, onAdd, children }: { title: string; onAdd: () => void; children: React.ReactNode }) { return <div className="landing-items"><div className="panel-heading"><strong>{title}</strong><button className="button secondary" type="button" onClick={onAdd}><Plus size={15} /> Add</button></div>{children}</div>; }
function RowActions({ visible, index, length, onVisible, onMove, onDelete }: { visible: boolean; index: number; length: number; onVisible: (visible: boolean) => void; onMove: (delta: number) => void; onDelete: () => void }) { return <div className="row-actions"><button className="text-button" type="button" onClick={() => onMove(-1)} disabled={index === 0}><ChevronUp size={15} /> Earlier</button><button className="text-button" type="button" onClick={() => onMove(1)} disabled={index === length - 1}><ChevronDown size={15} /> Later</button><button className="text-button" type="button" onClick={() => onVisible(!visible)}>{visible ? <EyeOff size={15} /> : <Eye size={15} />} {visible ? "Hide" : "Show"}</button><button className="text-button danger-text" type="button" onClick={onDelete}><Trash2 size={15} /> Delete</button></div>; }
function replace<T>(items: T[], index: number, changes: Partial<T>) { return items.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes, order: itemIndex } : item); }
function moveRow<T extends { order?: number }>(items: T[], index: number, delta: number) { const target = index + delta; if (target < 0 || target >= items.length) return items; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; return next.map((item, order) => ({ ...item, order })); }
function removeRow<T extends { order?: number }>(items: T[], index: number) { return items.filter((_, itemIndex) => itemIndex !== index).map((item, order) => ({ ...item, order })); }
function string(value: unknown, fallback = "") { return typeof value === "string" ? value : fallback; }
function number(value: unknown, fallback: number) { return typeof value === "number" ? value : fallback; }
function array<T>(value: unknown) { return Array.isArray(value) ? value as T[] : []; }
