"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function ShippingZoneEditor({ zone }: { zone: { id: string; name: string; countries: string[]; states: string[]; priority: number; active: boolean } }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const list = (name: string) => String(form.get(name) ?? "").split(",").map(value => value.trim().toUpperCase()).filter(Boolean); const response = await fetch(`/api/admin/shipping/zones/${zone.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), countries: list("countries"), states: list("states"), priority: Number(form.get("priority")), active: form.get("active") === "on" }) }); const result = await response.json().catch(() => ({})); setPending(false); setMessage(response.ok ? "Zone saved" : result.error ?? "Zone could not be saved"); if (response.ok) router.refresh(); }
  return <form className="shipping-zone-editor" onSubmit={save}><div className="field-grid"><label className="field">Zone name<input name="name" defaultValue={zone.name} /></label><label className="field">Countries (ISO codes)<input name="countries" defaultValue={zone.countries.join(", ")} placeholder="AU, NZ, US, CO" /></label><label className="field">States/regions (optional)<input name="states" defaultValue={zone.states.join(", ")} placeholder="SA, VIC" /></label><label className="field">Priority<input name="priority" type="number" defaultValue={zone.priority} /></label></div><div className="row-actions"><label className="check-field"><input name="active" type="checkbox" defaultChecked={zone.active} /><span>Zone enabled</span></label><button className="button secondary" disabled={pending}>{pending ? "Saving…" : "Save zone"}</button>{message && <span className={message === "Zone saved" ? "upload-success" : "upload-error"} role="status">{message}</span>}</div></form>;
}
