"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Settings = { storeName: string; businessName: string | null; supportEmail: string | null; currency: string; defaultCountry: string; siteTitle: string; siteDescription: string; defaultSocialImageUrl: string | null; socialLinks: Record<string, string | null>; shippingConfig: Record<string, number> };

export function StoreSettingsForm({ settings }: { settings: Settings }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setMessage("");
    const payload = { storeName: form.get("storeName"), businessName: form.get("businessName"), supportEmail: form.get("supportEmail"), currency: "AUD", defaultCountry: "AU", siteTitle: form.get("siteTitle"), siteDescription: form.get("siteDescription"), defaultSocialImageUrl: form.get("defaultSocialImageUrl"), instagram: form.get("instagram"), facebook: form.get("facebook"), tiktok: form.get("tiktok"), flatRateCents: Math.round(Number(form.get("flatRate")) * 100), freeOverCents: Math.round(Number(form.get("freeOver")) * 100) };
    const response = await fetch("/api/admin/settings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) return setMessage(result.error ?? "Settings could not be saved");
    setMessage("Settings saved"); router.refresh();
  }
  return <form className="admin-form" onSubmit={submit}><section className="admin-panel"><div className="panel-heading"><div><h2>Business identity</h2><p>Public store and support details.</p></div></div><div className="field-grid"><label className="field">Store name<input name="storeName" defaultValue={settings.storeName} required /></label><label className="field">Legal business name<input name="businessName" defaultValue={settings.businessName ?? ""} /></label><label className="field">Support email<input name="supportEmail" type="email" defaultValue={settings.supportEmail ?? ""} required /></label><label className="field">Market<input value="Australia · AUD · GST" disabled /></label></div></section><section className="admin-panel"><div className="panel-heading"><div><h2>Search defaults</h2><p>Used when a page has no specific SEO override.</p></div></div><label className="field">Site title<input name="siteTitle" defaultValue={settings.siteTitle} maxLength={70} required /></label><label className="field">Site description<textarea name="siteDescription" defaultValue={settings.siteDescription} maxLength={170} required /></label><label className="field">Default social image URL<input name="defaultSocialImageUrl" type="url" defaultValue={settings.defaultSocialImageUrl ?? ""} /></label></section><section className="admin-panel"><div className="panel-heading"><div><h2>Shipping and social</h2><p>Australian flat-rate checkout defaults and verified public links.</p></div></div><div className="field-grid"><label className="field">Flat shipping AUD<input name="flatRate" inputMode="decimal" defaultValue={((settings.shippingConfig.flatRateCents ?? 900) / 100).toFixed(2)} required /></label><label className="field">Free shipping over AUD<input name="freeOver" inputMode="decimal" defaultValue={((settings.shippingConfig.freeOverCents ?? 6000) / 100).toFixed(2)} required /></label><label className="field">Instagram URL<input name="instagram" type="url" defaultValue={settings.socialLinks.instagram ?? ""} /></label><label className="field">Facebook URL<input name="facebook" type="url" defaultValue={settings.socialLinks.facebook ?? ""} /></label><label className="field">TikTok URL<input name="tiktok" type="url" defaultValue={settings.socialLinks.tiktok ?? ""} /></label></div></section>{message && <div className={message === "Settings saved" ? "notice" : "form-error"}>{message}</div>}<div className="admin-form-actions"><button className="button">Save settings</button></div></form>;
}
