"use client";
import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
type Ticket = { id: string; orderNumber: string | null; kind: string; message: string; status: string; holdActive: boolean; responseDueAt: string | null; photoCount: number; replies: { author?: string; message?: string; at?: string }[] };
export function SupportPortal({ verified, guestEnabled, topics, helpText, responseDays, selectedOrder = "", account = false }: { verified: boolean; guestEnabled: boolean; topics: string[]; helpText: string; responseDays: number; selectedOrder?: string; account?: boolean }) {
  const [ready, setReady] = useState(verified), [challenge, setChallenge] = useState(""), [pending, setPending] = useState(false), [notice, setNotice] = useState("");
  const [tickets, setTickets] = useState<Ticket[]>([]), [orders, setOrders] = useState<{ orderNumber: string }[]>([]);
  async function load() {
    const response = await fetch("/api/support/tickets", { cache: "no-store" });
    const body = await response.json();
    if (!response.ok) { setReady(false); setNotice(body.error ?? "Please verify your email again."); return; }
    setTickets(body.tickets); setOrders(body.orders);
  }
  useEffect(() => { if (verified) void load().catch(() => setNotice("Could not load your tickets. Please refresh.")); }, [verified]);
  async function action(event: FormEvent<HTMLFormElement>, endpoint: string, method: string, payload: (data: FormData) => unknown) {
    event.preventDefault(); setPending(true); setNotice(""); const form = event.currentTarget;
    try {
      const response = await fetch(endpoint, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(payload(new FormData(form))) });
      const body = await response.json();
      if (!response.ok) { setNotice(body.error ?? "Could not complete your request"); return; }
      if (endpoint === "/api/support/access" && method === "POST") { setChallenge(body.challengeId); setNotice("Check your email for a code. It expires in 10 minutes."); }
      else if (endpoint === "/api/support/access") { setReady(true); setChallenge(""); await load(); }
      else { form.reset(); await load(); setNotice(body.held ? "Request received. Preparation is paused while our team reviews it. This is not a cancellation or refund approval." : "Your message has been received. Follow the response in your ticket."); }
    } catch { setNotice("Could not complete your request. Please try again."); } finally { setPending(false); }
  }
  async function submitTicket(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setNotice(""); const form = event.currentTarget, data = new FormData(form);
    try {
      const files = data.getAll("photos").filter((f): f is File => f instanceof File && f.size > 0);
      if (files.length > 3 || files.some(f => f.size > 512000 || !["image/jpeg", "image/png", "image/webp"].includes(f.type))) throw new Error("Choose up to 3 JPG, PNG or WebP photos, up to 500 KB each.");
      const attachments = await Promise.all(files.map(async file => ({ name: file.name, type: file.type, data: await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1]); reader.onerror = reject; reader.readAsDataURL(file); }) })));
      const response = await fetch("/api/support/tickets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: data.get("kind"), message: data.get("message"), orderNumber: data.get("orderNumber") || undefined, attachments }) });
      const body = await response.json();
      if (!response.ok) { setNotice(body.error ?? "Could not save your ticket"); return; }
      form.reset(); await load(); setNotice(body.held ? "Request received. Preparation is paused for review. This is not a cancellation or refund approval." : "Your request has been received. You can follow it below.");
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not send request"); } finally { setPending(false); }
  }
  return <div className="support-portal"><p>{helpText}</p><p>Our first-response target is {responseDays} business days, excluding weekends and store holidays. Requests and replies are managed here; email replies are not monitored.</p>
    {!ready && <section className="card"><h2>Access your tickets</h2><p>Sign in to your account, or verify your email to use support without creating an account. We show order information only after verification.</p><Link className="button secondary" href="/login?next=/support">Sign in</Link>{guestEnabled && (challenge ? <form className="form" onSubmit={event => action(event, "/api/support/access", "PATCH", data => ({ challengeId: challenge, code: data.get("code") }))}><label className="field">Verification code<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required /></label><button className="button" disabled={pending}>Verify email</button><button type="button" className="text-button" disabled={pending} onClick={() => { setChallenge(""); setNotice(""); }}>Use another email / resend</button></form> : <form className="form" onSubmit={event => action(event, "/api/support/access", "POST", data => ({ email: data.get("email") }))}><label className="field">Email address<input name="email" type="email" autoComplete="email" maxLength={254} required /></label><button className="button" disabled={pending}>{pending ? "Sending…" : "Send verification code"}</button></form>)}</section>}
    {ready && <><section className="card"><h2>Open a ticket</h2><form className="form" onSubmit={submitTicket}><label className="field">Topic<select name="kind">{topics.map(topic => <option key={topic} value={topic}>{topic.replaceAll("_", " ")}</option>)}</select></label><label className="field">Order (optional for general, account or privacy questions)<select name="orderNumber" defaultValue={selectedOrder}><option value="">No order / general enquiry</option>{orders.map(order => <option key={order.orderNumber} value={order.orderNumber}>{order.orderNumber}</option>)}</select></label><label className="field">Message<textarea name="message" minLength={10} maxLength={4000} required /></label><label className="field">Photos (optional)<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple /><small>Up to 3 photos, 500 KB each. Visible only to you and the support team.</small></label><p>Verified requests to change or cancel an order may pause preparation if work has not started. Our team reviews every request; submitting a ticket does not approve a cancellation or refund.</p><button className="button secondary" disabled={pending || !topics.length}>{pending ? "Sending…" : "Send request"}</button></form></section>
      <h2>Your tickets</h2>{!tickets.length && <p>You have no tickets yet.</p>}{tickets.map(ticket => <article className="card support-ticket" key={ticket.id}><h3>{ticket.kind.replaceAll("_", " ")}{ticket.orderNumber ? ` · ${ticket.orderNumber}` : ""}</h3><p>{ticket.status.replaceAll("_", " ")} · Reference {ticket.id.slice(0, 8)}</p>{ticket.holdActive && <p className="notice">Preparation paused pending review.</p>}{ticket.responseDueAt && <p>First-response target: {new Date(ticket.responseDueAt).toLocaleDateString("en-AU")}</p>}<p className="support-message">{ticket.message}</p>{Array.from({ length: ticket.photoCount }, (_, i) => <a key={i} href={`/api/account/support/${ticket.id}/photos/${i}`} target="_blank" rel="noreferrer">Photo {i + 1} </a>)}{Array.isArray(ticket.replies) && ticket.replies.map((reply, i) => <blockquote key={i}><strong>{reply.author === "customer" ? "You" : "Support team"}</strong><p className="support-message">{reply.message}</p><small>{reply.at ? new Date(reply.at).toLocaleString("en-AU") : ""}</small></blockquote>)}<form className="form" onSubmit={event => action(event, `/api/support/tickets/${ticket.id}/messages`, "POST", data => ({ message: data.get("message") }))}><label className="field">Follow up on this ticket<textarea name="message" minLength={2} maxLength={4000} required /></label><button className="button secondary" disabled={pending}>{ticket.status === "RESOLVED" ? "Reopen with a message" : "Send follow-up"}</button></form></article>)}{!account && <button className="text-button" disabled={pending} onClick={async () => { await fetch("/api/support/access", { method: "DELETE" }); setReady(false); setTickets([]); setOrders([]); setNotice("Guest support access cleared on this browser."); }}>Clear guest access on this browser</button>}</>}
    {notice && <p className="notice" role="status">{notice}</p>}</div>;
}
