import type { Metadata } from "next";
import Link from "next/link";

const published = "2026-09-08";
export const metadata: Metadata = { title: "How NFC pet tags work", description: "Learn how NFC pet tags work, what data stays on the tag, phone compatibility and privacy-conscious setup advice.", alternates: { canonical: "/guides/how-nfc-pet-tags-work" } };

export default function NfcPetTagGuide() {
  const origin = process.env.APP_URL ?? "http://localhost:3000";
  const data = { "@context": "https://schema.org", "@type": "Article", headline: "How NFC pet tags work", datePublished: published, dateModified: published, mainEntityOfPage: `${origin}/guides/how-nfc-pet-tags-work`, publisher: { "@id": `${origin}/#organization` } };
  return <article className="section compact-section article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replaceAll("<", "\\u003c") }} /><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/guides">Guides</Link><span>/</span><span>How NFC pet tags work</span></nav><header className="section-head"><span className="eyebrow">NFC pet tags · Australia</span><h1 className="page-title">How NFC pet tags work</h1><p className="lead">A smart pet tag opens a web profile when a finder taps it with a compatible phone. The important distinction is that the tag stores a public web address—not your private profile data.</p></header><h2>What happens after a tap?</h2><p>The phone reads the tag&apos;s short NFC record and offers to open its secure URL. The server then looks up the tag&apos;s current status and public profile. Because the destination is managed online, the owner can update contact or medical details without replacing or rewriting the physical tag.</p><h2>NFC and QR work together</h2><p>NFC is convenient, but not every person knows where their phone&apos;s reader is. A printed QR code provides a familiar fallback and should resolve to the same protected public identifier.</p><h2>What information should be public?</h2><p>Keep the first screen useful and minimal: the pet&apos;s name, a short owner message, urgent medical or behavioural warnings, and one or two phone contacts. Avoid publishing a residential address, personal routines, account identifiers, or anything that does not help a finder act safely.</p><h2>Does an NFC tag track location?</h2><p>A passive NFC tag has no GPS and cannot silently track a pet. A finder may choose to share their phone location through an explicit action; the browser must request permission before any coordinates are used.</p><h2>Before relying on a tag</h2><p>Test both NFC and QR with more than one phone, verify the emergency numbers, keep the printed text legible, and periodically confirm that the public page shows only the information you intend to share.</p><p><Link className="button" href="/shop">Explore NFC pet tags</Link></p></article>;
}
