import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {getAdminApiContext,hasPermission} from "@/lib/admin";
import {db} from "@/lib/db";
import {assertSameOrigin,jsonError} from "@/lib/http";
import {addressSchema} from "@/lib/address-validation";
const schema=z.object({address:addressSchema,reason:z.string().trim().min(10).max(500),confirmed:z.literal(true)});
export async function PATCH(request:NextRequest,{params}:{params:Promise<{orderId:string}>}){if(!assertSameOrigin(request))return jsonError("Invalid origin",403);const context=await getAdminApiContext();if(!context||!hasPermission(context,"orders.address"))return jsonError("Address approval permission required",403);const input=schema.safeParse(await request.json().catch(()=>null));if(!input.success)return jsonError("Check the address and add a reason of at least 10 characters");const {orderId}=await params;const a=input.data.address;
 const changed=await db.$transaction(async tx=>{const order=await tx.order.findFirst({where:{id:orderId,storeId:context.store.id},include:{shipments:{select:{id:true}}}});if(!order)return "missing";if(!["PAID","PROCESSING"].includes(order.status)||order.shipments.length||a.country!==order.shippingCountry||a.postcode!==order.shippingPostcode||a.locality!==order.shippingLocality)return "locked";await tx.order.update({where:{id:order.id},data:{shippingName:a.recipient,shippingCompany:a.company??null,shippingLine1:a.line1,shippingLine2:a.line2??null,shippingPhone:a.phone??null,shippingDependentLocality:a.dependentLocality??null,shippingAdministrativeArea:a.administrativeArea??null,shippingState:a.administrativeArea??null,shippingFormattedAddress:null,shippingAddressId:null}});await tx.auditLog.create({data:{actorId:context.user.id,storeId:context.store.id,action:"ORDER_ADDRESS_CORRECTED",entityType:"Order",entityId:order.id,metadata:{reason:input.data.reason,before:{recipient:order.shippingName,line1:order.shippingLine1,line2:order.shippingLine2},after:a}}});return "ok";},{isolationLevel:"Serializable"}).catch(()=>"conflict");if(changed!=="ok")return jsonError(changed==="missing"?"Not found":changed==="locked"?"Address locked: labels exist, fulfilment has advanced, or the new destination requires a new delivery quote. Review with the shipping team.":"Order changed. Refresh and try again.",changed==="missing"?404:409);return NextResponse.json({ok:true});}
