import Link from "next/link";
import { notFound } from "next/navigation";
import { CategoryEditor, type CategoryEditorInitial } from "@/components/category-editor";
import { allCategoryBenefits, allCategoryFaq, allCategorySections, allCategorySteps, allCategoryUseCases } from "@/lib/category-content";
import { db } from "@/lib/db";
import { requireAdminPageContext } from "@/lib/admin";
import { LandingSectionEditor } from "@/components/landing-section-editor";

export default async function EditCategoryPage({ params }: { params: Promise<{ categoryId: string }> }) {
  const { categoryId } = await params;
  const { store } = await requireAdminPageContext();
  const category = await db.productCategory.findFirst({ where: { id: categoryId, storeId: store.id }, include: { products: { where: { storeId: store.id }, select: { id: true, name: true, status: true }, orderBy: { name: "asc" } }, landingSections: { orderBy: { sortOrder: "asc" } } } });
  if (!category) notFound();
  const initial: CategoryEditorInitial = { id: category.id, name: category.name, slug: category.slug, shortDescription: category.shortDescription ?? "", description: category.description ?? "", icon: category.icon ?? "", imageUrl: category.imageUrl ?? "", cardTitle: category.cardTitle ?? "", cardText: category.cardText ?? "", cardImageUrl: category.cardImageUrl ?? "", cardImageAlt: category.cardImageAlt ?? "", heroEyebrow: category.heroEyebrow ?? "", heroHeadline: category.heroHeadline ?? "", heroDescription: category.heroDescription ?? "", heroImageUrl: category.heroImageUrl ?? "", heroImageAlt: category.heroImageAlt ?? "", secondaryImageUrl: category.secondaryImageUrl ?? "", ctaLabel: category.ctaLabel ?? "", ctaHref: category.ctaHref ?? "", secondaryCtaLabel: category.secondaryCtaLabel ?? "", secondaryCtaHref: category.secondaryCtaHref ?? "", finalCtaEyebrow: category.finalCtaEyebrow ?? "", finalCtaHeadline: category.finalCtaHeadline ?? "", finalCtaDescription: category.finalCtaDescription ?? "", finalCtaLabel: category.finalCtaLabel ?? "", finalCtaHref: category.finalCtaHref ?? "", visualTheme: category.visualTheme, landingLayout: category.landingLayout, status: category.status, sortOrder: category.sortOrder, showOnHomepage: category.showOnHomepage, showInNavigation: category.showInNavigation, showInShop: category.showInShop, showLanding: category.showLanding, seoTitle: category.seoTitle ?? "", seoDescription: category.seoDescription ?? "", ogImageUrl: category.ogImageUrl ?? "", canonicalUrl: category.canonicalUrl ?? "", indexable: category.indexable, benefits: allCategoryBenefits(category.benefits), useCases: allCategoryUseCases(category.useCases), howItWorks: allCategorySteps(category.howItWorks), contentSections: allCategorySections(category.contentSections), faq: allCategoryFaq(category.faq) };
  return <div><Link className="admin-back" href="/admin/categories">← Categories</Link><div className="admin-heading"><div><p className="admin-kicker">Content</p><h1>{category.name}</h1><p>Commercial visibility is independent from every existing tag.</p></div><span className={`admin-status large ${category.status}`}>{category.status}</span></div><section className="admin-panel"><div className="panel-heading"><div><h2>Products in this category</h2><p>Assign or move products from each product editor.</p></div><Link href="/admin/products/new" className="button secondary">Add product</Link></div><div className="compact-list">{category.products.map(product => <Link href={`/admin/products/${product.id}`} key={product.id}><strong>{product.name}</strong><span className={`admin-status ${product.status}`}>{product.status}</span></Link>)}</div>{!category.products.length && <div className="admin-empty">No products assigned yet.</div>}</section><LandingSectionEditor categoryId={category.id} initial={category.landingSections.map(section => ({ id: section.id, type: section.type, name: section.name, visible: section.visible, content: section.content as Record<string, unknown> }))} /><CategoryEditor initial={initial} /></div>;
}
