import Link from "next/link";
import { Prisma, StoreCapability } from "@prisma/client";
import { Search } from "lucide-react";
import { db } from "@/lib/db";
import { requireAdminPageContext } from "@/lib/admin";
import { hasStoreCapability } from "@/lib/storefront";
import { notFound } from "next/navigation";

const statuses = ["MANUFACTURED", "UNCLAIMED", "ACTIVE", "LOST", "DISABLED", "REPLACED"] as const;
const PAGE_SIZE = 50;

function date(value?: string, end = false) { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const result = new Date(`${value}T${end ? "23:59:59.999" : "00:00:00.000"}Z`); return Number.isNaN(result.getTime()) ? undefined : result; }

export default async function AdminTagsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; product?: string; category?: string; batch?: string; createdFrom?: string; createdTo?: string; activatedFrom?: string; activatedTo?: string; page?: string }> }) {
  const { store } = await requireAdminPageContext();
  if (!hasStoreCapability(store, StoreCapability.NFC)) notFound();
  const params = await searchParams; const q = params.q?.trim() ?? ""; const status = statuses.find(value => value === params.status); const page = Math.max(1, Number(params.page) || 1);
  const createdFrom = date(params.createdFrom); const createdTo = date(params.createdTo, true); const activatedFrom = date(params.activatedFrom); const activatedTo = date(params.activatedTo, true);
  const where: Prisma.NFCTagWhereInput = { storeId: store.id, ...(q ? { OR: [{ publicTagId: { contains: q, mode: "insensitive" } }, { owner: { is: { name: { contains: q, mode: "insensitive" } } } }, { owner: { is: { email: { contains: q, mode: "insensitive" } } } }, { product: { is: { name: { contains: q, mode: "insensitive" } } } }, { productVariant: { is: { sku: { contains: q, mode: "insensitive" } } } }, { manufacturingBatch: { is: { batchNumber: { contains: q, mode: "insensitive" } } } }, { orderItem: { is: { order: { is: { orderNumber: { contains: q, mode: "insensitive" } } } } } }] } : {}), ...(status ? { status } : {}), ...(params.product ? { productId: params.product } : {}), ...(params.category ? { product: { storeId: store.id, categoryId: params.category } } : {}), ...(params.batch ? { manufacturingBatchId: params.batch } : {}), ...(createdFrom || createdTo ? { createdAt: { ...(createdFrom ? { gte: createdFrom } : {}), ...(createdTo ? { lte: createdTo } : {}) } } : {}), ...(activatedFrom || activatedTo ? { activatedAt: { ...(activatedFrom ? { gte: activatedFrom } : {}), ...(activatedTo ? { lte: activatedTo } : {}) } } : {}) };
  const [tags, total, products, categories, batches] = await Promise.all([
    db.nFCTag.findMany({ where, include: { product: { select: { name: true } }, productVariant: { select: { sku: true } }, owner: { select: { name: true, email: true } }, orderItem: { select: { order: { select: { orderNumber: true } } } }, manufacturingBatch: { select: { id: true, batchNumber: true } }, _count: { select: { scans: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE }),
    db.nFCTag.count({ where }), db.product.findMany({ where: { storeId: store.id }, select: { id: true, name: true }, orderBy: { name: "asc" } }), db.productCategory.findMany({ where: { storeId: store.id }, select: { id: true, name: true }, orderBy: { name: "asc" } }), db.manufacturingBatch.findMany({ where: { storeId: store.id }, select: { id: true, batchNumber: true }, orderBy: { createdAt: "desc" }, take: 200 }),
  ]);
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE)); const query = new URLSearchParams(Object.entries(params).flatMap(([key, value]) => value && key !== "page" ? [[key, value]] : []));
  return <div><div className="admin-heading"><div><p className="admin-kicker">NFC operations</p><h1>Tags</h1><p>Search by identity, owner, order, product, SKU or manufacturing history.</p></div></div><form className="admin-filters tag-filters"><label><Search size={17} /><input name="q" defaultValue={q} placeholder="Tag ID, owner, order, product, SKU or batch" /></label><select name="status" defaultValue={params.status ?? ""}><option value="">All statuses</option>{statuses.map(value => <option key={value}>{value}</option>)}</select><select name="category" defaultValue={params.category ?? ""}><option value="">All categories</option>{categories.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select name="product" defaultValue={params.product ?? ""}><option value="">All products</option>{products.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select name="batch" defaultValue={params.batch ?? ""}><option value="">All batches</option>{batches.map(item => <option value={item.id} key={item.id}>{item.batchNumber}</option>)}</select><label className="date-filter">Created from<input type="date" name="createdFrom" defaultValue={params.createdFrom} /></label><label className="date-filter">Created to<input type="date" name="createdTo" defaultValue={params.createdTo} /></label><label className="date-filter">Activated from<input type="date" name="activatedFrom" defaultValue={params.activatedFrom} /></label><label className="date-filter">Activated to<input type="date" name="activatedTo" defaultValue={params.activatedTo} /></label><button className="button secondary">Filter</button></form><section className="admin-panel flush">{tags.length ? <div className="admin-table tag-admin-table"><div className="admin-tr admin-th"><span>Tag</span><span>Product</span><span>Owner / order</span><span>Scans</span><span>Status</span></div>{tags.map(tag => <Link href={`/admin/tags/${tag.id}`} className="admin-tr" key={tag.id}><span><strong>{tag.publicTagId}</strong><small>{tag.manufacturingBatch?.batchNumber ?? "Legacy unit"}</small></span><span><strong>{tag.product.name}</strong><small>{tag.productVariant?.sku ?? tag.productType}</small></span><span>{tag.owner ? <><strong>{tag.owner.name}</strong><small>{tag.owner.email}</small></> : <strong>Unowned</strong>}<small>{tag.orderItem?.order.orderNumber ?? "No linked order"}</small></span><strong>{tag._count.scans}</strong><span className={`admin-status ${tag.status}`}>{tag.status}</span></Link>)}</div> : <div className="admin-empty">No tags match this view.</div>}</section>{pages > 1 && <nav className="pagination" aria-label="Tag pages"><Link className={page <= 1 ? "disabled" : ""} href={`/admin/tags?${query}&page=${Math.max(1, page - 1)}`}>Previous</Link><span>Page {page} of {pages}</span><Link className={page >= pages ? "disabled" : ""} href={`/admin/tags?${query}&page=${Math.min(pages, page + 1)}`}>Next</Link></nav>}</div>;
}
