import Link from "next/link";
import { Search } from "lucide-react";
import { db } from "@/lib/db";

const statuses = ["MANUFACTURED", "UNCLAIMED", "ACTIVE", "DISABLED", "LOST", "REPLACED"] as const;

export default async function AdminTagsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const { q = "", status = "" } = await searchParams; const validStatus = statuses.find(value => value === status);
  const tags = await db.nFCTag.findMany({ where: { ...(q ? { OR: [{ publicTagId: { contains: q, mode: "insensitive" } }, { product: { name: { contains: q, mode: "insensitive" } } }, { owner: { email: { contains: q, mode: "insensitive" } } }] } : {}), ...(validStatus ? { status: validStatus } : {}) }, include: { product: { select: { name: true } }, productVariant: { select: { sku: true } }, owner: { select: { name: true, email: true } }, manufacturingBatch: { select: { id: true, batchNumber: true } }, _count: { select: { scans: true } } }, orderBy: { createdAt: "desc" }, take: 300 });
  return <div><div className="admin-heading"><div><p className="admin-kicker">NFC operations</p><h1>Tags</h1><p>Search, trace, block and inspect every physical unit.</p></div></div><form className="admin-filters"><label><Search size={17} /><input name="q" defaultValue={q} placeholder="Tag ID, product or owner email" /></label><select name="status" defaultValue={status}><option value="">All statuses</option>{statuses.map(value => <option key={value}>{value}</option>)}</select><button className="button secondary">Filter</button></form><section className="admin-panel flush">{tags.length ? <div className="admin-table tag-admin-table"><div className="admin-tr admin-th"><span>Tag</span><span>Product</span><span>Owner</span><span>Scans</span><span>Status</span></div>{tags.map(tag => <Link href={`/admin/tags/${tag.id}`} className="admin-tr" key={tag.id}><span><strong>{tag.publicTagId}</strong><small>{tag.manufacturingBatch?.batchNumber ?? "Legacy unit"}</small></span><span><strong>{tag.product.name}</strong><small>{tag.productVariant?.sku ?? tag.productType}</small></span><span>{tag.owner ? <><strong>{tag.owner.name}</strong><small>{tag.owner.email}</small></> : "Unowned"}</span><strong>{tag._count.scans}</strong><span className={`admin-status ${tag.status}`}>{tag.status}</span></Link>)}</div> : <div className="admin-empty">No tags match this view.</div>}</section></div>;
}
